/* Verify active Week11–14 supplement controls; browser output stays outside repository. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),fs=require('fs'),path=require('path');
const base=(process.argv[2]||'http://127.0.0.1:8873/courses/aa').replace(/\/$/,''),out=process.argv[3]||path.join(require('os').tmpdir(),'extra-w11-w14.json');
(async()=>{const b=await chromium.launch({headless:true}),p=await b.newPage({viewport:{width:1366,height:1000}}),rep=[],failures=[],errors=[];p.setDefaultTimeout(3000);p.on('pageerror',e=>errors.push(e.message));p.on('console',e=>{if(e.type()==='error')errors.push(e.text())});
const check=(name,ok)=>{rep.push({name,ok});console.log(name,ok);if(!ok)failures.push(name)};
let active=0;const choose=async(i)=>{active=i;await p.locator('#animation-choice').selectOption(String(i))};
const host=()=>p.locator(`.animation-panel[data-animation-panel="${active}"] .widget.anim`);
const click=async(text)=>host().getByRole('button',{name:text,exact:true}).click();
const end=async()=>{for(const r of await host().locator('input[aria-label="Animation step"]').all())await r.evaluate(e=>{e.value=e.max;e.dispatchEvent(new Event('input',{bubbles:true}))})};
const controls=async()=>{const h=host();let n=0;for(const e of await h.locator('select').all()){const old=await e.inputValue();for(const v of await e.locator('option').evaluateAll(es=>es.map(e=>e.value))){await e.selectOption(v);n++}await e.selectOption(old)}for(const e of await h.locator('input[type=range]').all()){await e.evaluate(e=>{for(const v of [e.min,e.max,e.min]){e.value=v;e.dispatchEvent(new Event('input',{bubbles:true}))}});n+=3}for(const title of ['Step forward','Step back','Back to start']){const a=h.locator(`[title="${title}"]`);if(await a.count()&&await a.isEnabled()){await a.click();n++}}const play=h.locator('[title="Play or pause"]');if(await play.count()){await play.click();await p.waitForTimeout(30);await play.click();n+=2}await end();return n};
for(const w of [11,12,13,14]){await p.goto(`${base}/w${w}/ek-notlar/`,{waitUntil:'domcontentloaded'});for(const tab of ['lesson','practice','notes']){await p.locator(`[data-week-tab="${tab}"]`).click();await p.locator(`#${tab} details`).evaluateAll(es=>es.forEach(e=>e.open=true));check(`W${w} extra tab ${tab}`,await p.locator(`#${tab}`).isVisible())}await p.locator('[data-week-tab=lesson]').click();check(`W${w} animation mount`,!(await p.locator('body').innerText()).includes('could not start'));
if(w===11){await choose(0);const buttons=host().locator('.aa-cell');const total=await buttons.count();for(let i=0;i<total;i++){if(i===0||i===total-1)continue;await buttons.nth(i).click()}await click('clear walls');const n=await controls();rep.push({w,animation:'Dijkstra terrain',controls:n+total-1,text:await host().locator('.anim-msg').last().innerText()});check('W11 grid reaches endpoint',!(await host().locator('.anim-msg').last().innerText()).includes('unreachable'))}
if(w===13){await choose(0);const inputs=host().locator('input[type=text]');await inputs.nth(0).fill('😀a');await inputs.nth(1).fill('a');await click('use');await end();check('W13 extra Unicode edit',/distance\(😀a, a\) = 1/.test(await host().locator('.anim-msg').innerText()));await inputs.nth(0).fill('');await inputs.nth(1).fill('abc');await click('use');await end();check('W13 extra empty edit base',/distance\(, abc\) = 3/.test(await host().locator('.anim-msg').innerText()));await inputs.nth(0).fill('123456789');await click('use');rep.push({w,oversize:await host().locator('.anim-msg').innerText()});check('W13 extra oversized input rejected without truncation',/at most 8/.test(await host().locator('.anim-msg').innerText())&&(await inputs.nth(0).inputValue())==='123456789');await inputs.nth(0).fill('kitten');await inputs.nth(1).fill('sitting');await click('use');rep.push({w,controls:await controls()});check('W13 extra kitten3',/distance\(kitten, sitting\) = 3/.test(await host().locator('.anim-msg').innerText()))}
if(w===14){await choose(0);await click('show all four');for(const e of await host().locator('.w14-pick [role=button]').all())await e.click();const q=host().locator('.w14-q button');for(const i of [0,1,3,2])await q.nth(i).click();check('W14 diagnosis quiz both branches',await host().locator('.w14-q button.right').count()===1);await click('2 · trace a small run');for(const variant of ['report.py (as given)','report_fixed.py']){await click(variant);await controls();rep.push({w,mode:'diagnose trace '+variant,text:await host().innerText()})}check('W14 repaired report total57',/57/.test(await host().innerText())&&!/total = 228/.test(await host().innerText()));await click('3 · count the growth');for(const e of await host().locator('button').all())if(await e.isVisible()&&!(await e.innerText()).match(/^(1 ·|2 ·|3 ·)/))await e.click();await p.waitForFunction(()=>document.querySelector('[data-anim=w14-diagnose]')?.querySelectorAll('tbody tr').length===4);check('W14 diagnosis growth complete',true);rep.push({w,mode:'diagnose growth',text:await host().innerText()});
await choose(1);for(const target of ['13 (a pair exists)','100 (no pair: worst case)']){await click(target);for(const variant of ['obvious · every pair','set · one pass']){await click(variant);await controls();rep.push({w,mode:'twoSum '+target+' '+variant,text:await host().locator('.anim-msg').innerText()})}}await host().locator('input[type=number]').fill('2.5');await click('use');await end();check('W14 twoSum still visible',await host().isVisible());check('W14 noninteger target handled without truncation',/False|No pair/.test(await host().innerText()));await host().locator('input[type=number]').fill('');await click('use');check('W14 empty target rejected',await host().locator('input[type=number]').evaluate(e=>!!e.validationMessage));await click('2 · benchmark 2 000 → 8 000');for(const e of await host().locator('button').all())if(await e.isVisible()&&!/^[12] ·/.test(await e.innerText()))await e.click();await p.waitForFunction(()=>document.querySelector('[data-anim=w14-two-sum]')?.querySelectorAll('tbody tr').length===3);check('W14 twoSum benchmark complete',true);rep.push({w,mode:'twoSum bench',text:await host().innerText()});
await choose(2);for(const variant of ['as submitted','after your review']){await click(variant);await controls();const answers=host().locator('button').filter({hasText:/^(yes|no)$/});for(const a of await answers.all())if(await a.isEnabled())await a.click();const qs=host().locator('.w14-q:not(.w14-yn) button');for(const i of [0,2,1])if(await qs.nth(i).isEnabled())await qs.nth(i).click();rep.push({w,mode:'review '+variant,text:await host().innerText()})}
await choose(3);for(const pattern of ['search in loop','concatenation','front of list','sort in loop','total every round']){await click(pattern);for(const t of ['×2','×4','a bit more than ×4','×8'])await click(t);await controls();if(pattern==='concatenation'){await click('in-place resize (CPython sometimes)');await end();await click('repeated-copy model');await end()}rep.push({w,mode:'trap '+pattern,text:await host().innerText()})}
await choose(4);for(const t of ['summarise_slow','dict.get (called thousands of times)'])await click(t);await controls();for(const e of await host().locator('.w14-pick [role=button]').all())if(await e.isVisible())await e.click();await click('▶ run the focused benchmark');await p.waitForTimeout(50);const play=host().locator('[title="Play or pause"]');for(const a of await play.all())if(await a.isVisible())await a.click();await end();await p.waitForFunction(()=>document.querySelector('[data-anim=w14-profile]')?.querySelectorAll('tbody tr').length===4);const qs=host().locator('.w14-q:not(.w14-yn)');for(const [q,order] of [[qs.nth(0),[0,2,1]],[qs.nth(1),[0,1,2]]])for(const i of order)await q.locator('button').nth(i).click();check('W14 profile final quiz branches',await host().locator('.w14-q button.right').count()===2);check('W14 profile benchmark complete',true);rep.push({w,mode:'profile',text:await host().innerText()});}
}
check('Extra console/runtime',errors.length===0);fs.writeFileSync(out,JSON.stringify({rep,failures,errors},null,2));await b.close();if(failures.length)process.exitCode=1})().catch(e=>{console.error(e);process.exit(1)});
