/* Browser checks against production lesson helpers and independent small-instance oracles.
 * Serve the repository and pass its AA URL as the first argument; requires Playwright. */
const base=(process.argv[2]||'http://127.0.0.1:8873/courses/aa').replace(/\/$/,'');
const reportFile=process.argv[3]||require('path').join(require('os').tmpdir(),'simple-w11-w14.json');
const {chromium}=require('playwright');const fs=require('fs');const path=require('path');const root=path.resolve(__dirname,'..');
(async()=>{const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const rep=[];let failures=[];const check=(name,value)=>{console.log(name,JSON.stringify(value));rep.push({name,value});if(value!==true)failures.push(name)};
for(let w=11;w<=14;w++){const errors=[];page.removeAllListeners('pageerror');page.on('pageerror',e=>errors.push(e.message));await page.goto(`${base}/w${w}/`,{waitUntil:"domcontentloaded"});
const sweep=await page.evaluate(async()=>{let selectChanges=0,rangeChanges=0,buttonClicks=0;const event=(e,t)=>e.dispatchEvent(new Event(t,{bubbles:true}));
for(const e of [...document.querySelectorAll('.try select')]){const old=e.value;for(const v of [...e.options].map(o=>o.value)){if([...e.options].some(o=>o.value===v)){e.value=v;event(e,'change');selectChanges++}}e.value=old;event(e,'change')}
for(const e of document.querySelectorAll('.try input[type=range]')){const old=e.value;for(const v of [e.min,e.max,old]){e.value=v;event(e,'input');rangeChanges++}}
for(const b of [...document.querySelectorAll('.try button')]){if(!b.isConnected||b.textContent.includes('Oynat')||b.textContent.includes('Play'))continue;b.click();buttonClicks++}
let playClicks=0;for(const b of [...document.querySelectorAll('.try button')]){if(!b.isConnected||!/(Oynat|Play)/i.test(b.textContent)||b.disabled)continue;b.click();await new Promise(r=>setTimeout(r,25));if(b.isConnected&&/(Dur|Pause|Durdur)/i.test(b.textContent))b.click();playClicks++}return {selectChanges,rangeChanges,buttonClicks,playClicks}});await page.waitForTimeout(150);rep.push({w,sweep,errors});console.log('sweep',w,JSON.stringify(sweep),errors);
if(w===11){check('W11 BF negative DAG',await page.evaluate(()=>{const G=__t.parseG('S>A 4, S>B 2, B>A -3, A>C 1, B>C 5');const r=__t.bfFinal(G,'S');return r.dist.C===0&&!r.neg}));rep.push({name:'W11 helpers',v:await page.evaluate(()=>({bf:__t.bfFinal(__t.parseG('S>A 1,A>B -2,B>A 1'),'S'),dij:__t.dijkRun(__t.parseG('S>A 4,S>B 2,B>A -3,A>C 1'),'S')}))});check('W11 reserved-name rejection',await page.evaluate(()=>__t.parseG('__proto__>A 3').bad.length>0));check('W11 ragged-grid rejection',await page.evaluate(()=>__t.parseGrid('S..\n.G')===null));}
if(w===12){check('W12 nqueen n2..10',await page.evaluate(()=>[2,3,4,5,6,7,8,9,10].map(n=>nqCount(n).sols).join(',')==='0,0,2,10,4,40,92,352,724'));rep.push({name:'W12 queen result shape',v:await page.evaluate(()=>nqCount(4))});check('W12 grid126',await page.evaluate(()=>{GR={r:5,c:6,obs:new Set()};return grCompute().dp[4][5]===126}));check('W12 derangements pruned vs full',await page.evaluate(()=>{const leaves=r=>r.children?.length?r.children.flatMap(leaves):r.ok?[r]:[];return countNodes(buildBT('derP',4))<countNodes(buildBT('derN',4))}));}
if(w===13){check('W13 edit kitten',await page.evaluate(()=>{const e=editDP('kitten','sitting');return e.D[6][7]===3&&applyOps('kitten',editTrace(e).ops)==='sitting'}));check('W13 standard DP examples',await page.evaluate(()=>coinDP([1,3,4],6).best[6]===2&&knapDP([[1,1],[3,4],[4,5],[5,7]],7).V[4][7]===9&&subsetDP([3,34,4,12,5,2],9).ok&&partDP([3,1,4,1,5,9,2,6],3).best===14&&eggDP(2,100).E[2][100]===14&&breakDP(10,[2,5]).cost===15&&kadane([-2,1,-3,4,-1,2,1,-5,4]).max===6&&wisDP([['A',0,4,5],['B',3,7,6],['C',4,8,5]]).best===10));check('W13 shuffle good/bad',await page.evaluate(()=>shuffleDP('chocolate','chips','cchocohilaptes').ok&&!shuffleDP('chocolate','chips','chocochilatspe').ok));check('W13 LCS known',await page.evaluate(()=>lcsDP('AGGTAB','GXTXAYB')[6][7]===4&&lisDirect([3,1,4,1,5,9,2,6],true)===4));check('W13 DTW zero',await page.evaluate(()=>dtwDP([1,3,3,1],[1,3,1]).cost===0));
await page.locator('#w_edit input[data-k=s]').fill('😀a');await page.locator('#w_edit input[data-k=t]').fill('a');await page.locator('#w_edit [data-a=end]').click();await page.locator('#w_edit [data-a=trace]').click();check('W13 Unicode edit output',await page.locator('#w_edit [data-sum]').innerText().then(t=>t.includes('✓ = T')&&t.includes('maliyet = 1')));
await page.locator('#w_coin input[data-k=c]').fill('bad');await page.locator('#w_coin [data-a=play]').click();await page.waitForTimeout(100);check('W13 invalid-stepper cleared',await page.locator('#w_coin [data-mat]').innerText().then(t=>!t));}
if(w===14){check('W14 graph duality all3',await page.evaluate(()=>{const E=[[0,1],[1,2],[2,3],[3,0]];return minVC(4,E).length===2&&maxClique(4,cmpEdges(4,E)).length===2}));await page.locator('#sa_in').fill('{};x');check('W14 emptyclause UNSAT',await page.locator('#sa_sum').innerText().then(t=>t.includes('SAĞLANAMAZ')));await page.locator('#ch_in').fill('~~x');check('W14 invalidliteral rejected',await page.locator('#ch_out').innerText().then(t=>t.includes('literal yazın')));await page.locator('#ed_a').fill('😀a');await page.locator('#ed_b').fill('a');check('W14 Unicode edit output',await page.locator('#ed_o').innerText().then(t=>t.includes('Uzaklık = 1')&&t.includes('3×2')));
const chains=await page.evaluate(()=>{for(let k=1;k<=8;k++){const z=Array.from({length:k},(_,i)=>({v:'a'+i,neg:false})),{cl,nw,names}=chainClauses(z);for(let mask=0;mask<(1<<k);mask++){const v={};z.forEach((l,i)=>v[l.v]=!!(mask>>i&1));const orig=z.some(l=>v[l.v]);let sat=false;for(let t=0;t<(1<<nw);t++){names.forEach((nm,i)=>v[nm]=!!(t>>i&1));if(cl.every(c=>c.some(l=>v[l.v]!==l.neg)))sat=true}if(sat!==orig)return false}}return true});check('W14 chain allassignments k1..8',chains);
for(const mode of ['sat','ss','ham']){await page.locator('#cv_mode').selectOption(mode);if(await page.locator('#cv_vb').count())await page.locator('#cv_vb').click();rep.push({name:'cert '+mode,out:await page.locator('#cv_out').innerText().catch(()=> '')})}}
check(`W${w} console/runtime`,errors.length===0);
// Quiz branches: extract literal arrays, W13 has named constants.
await page.reload();const source=fs.readFileSync(path.join(root,`w${w}`,'index.html'),'utf8');let Qs=[];
if(w===13)Qs=await page.evaluate(()=>[{id:'#quiz0',Q:QUIZ0},{id:'#quiz1',Q:QUIZ1}]);else {const re=/mkQuiz\("(#quiz\w+)",\s*\[/g;for(const m of source.matchAll(re)){let at=m.index+m[0].length-1,end=at,depth=0,q='',escaped=false;for(;end<source.length;end++){const c=source[end];if(q){if(escaped)escaped=false;else if(c==='\\')escaped=true;else if(c===q)q='';continue}if(c==='"'||c==="'"||c==='`'){q=c;continue}if(c==='[')depth++;if(c===']'&&--depth===0){end++;break}}try{Qs.push({id:m[1],Q:eval(source.slice(at,end))})}catch(e){rep.push({quizParse:m[1],error:e.message})}}}
for(const {id,Q} of Qs){for(let qi=0;qi<Q.length;qi++){const correct=Q[qi][1][Q[qi][2]],box=page.locator(`${id} [data-q="${qi}"]`);const opts=box.locator('button.opt');const texts=await opts.allTextContents();let ix=texts.findIndex(t=>t===correct);if(ix<0)ix=Q[qi][2];await opts.nth(ix).click()}const score=await page.locator(`${id} [data-score]`).innerText();rep.push({w,id,branch:'correct',score});check(`W${w} ${id} all correct`,score.includes(`${Q.length} / ${Q.length}`))}
await page.reload();for(const {id,Q} of Qs){for(let qi=0;qi<Q.length;qi++){const correct=Q[qi][1][Q[qi][2]],opts=page.locator(`${id} [data-q="${qi}"] button.opt`),texts=await opts.allTextContents();let ix=texts.findIndex(t=>t!==correct);await opts.nth(Math.max(0,ix)).click()}const score=await page.locator(`${id} [data-score]`).innerText();rep.push({w,id,branch:'wrong',score});check(`W${w} ${id} all wrong`,score.includes(`0 / ${Q.length}`))}
}
fs.writeFileSync(reportFile,JSON.stringify({rep,failures},null,2));await browser.close();console.log('failures',failures);if(failures.length)process.exitCode=1})().catch(e=>{console.error(e);process.exitCode=1});
