/* Independent browser oracles for AA simple pages. Run against a local server with
 * AA_BASE_URL=http://127.0.0.1:8873/courses/aa and Playwright installed.
 * PLAYWRIGHT_MODULE can name an absolute module path; AA_REPORT_DIR optionally saves JSON.
 * Temporary helper exports instrument responses only, leaving production assets unchanged. */
const fs=require('fs'),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const BASE_URL=(process.env.AA_BASE_URL||'http://127.0.0.1:8873/courses/aa').replace(/\/$/,'');
(async()=>{const b=await chromium.launch({headless:true});const results=[];
function expose(js){if(!js.includes('const SYM='))return js;const at=js.lastIndexOf('});');return js.slice(0,at)+'Object.assign(window,{SYM,r0_specRun,r0_nnTour,r0_lineOpt,IV,r0_pickIv,r0_knGreedy,r0_knBrute,CTP,r0_search});\n'+js.slice(at)}
async function load(route){
 const p=await b.newPage({viewport:{width:1280,height:900}});p.errors=[];p.on('pageerror',e=>p.errors.push(e.message));
 await p.route('**/*',r=>new URL(r.request().url()).origin===new URL(BASE_URL).origin?r.continue():r.abort());
 if(route==='w3')await p.route('**/aa/**',async r=>{const type=r.request().resourceType();if(type!=='document'&&type!=='script')return r.continue();const res=await r.fetch({maxRetries:3});let source=await res.text();source=type==='script'?expose(source):source.replace(/(<script\b[^>]*>)([\s\S]*?)(<\/script>)/g,(all,a,js,c)=>a+expose(js)+c);await r.fulfill({response:res,body:source})});
 await p.goto(`${BASE_URL}/${route}/`,{waitUntil:'domcontentloaded'});return p;
}
let p=await load('w3');let r=await p.evaluate(()=>{const failures=[],cases=[];let assertions=0;const ok=(v,msg)=>{assertions++;if(!v)failures.push(msg)},eq=(a,b,msg)=>ok(JSON.stringify(a)===JSON.stringify(b),msg),set=(id,val,event='input')=>{const el=document.getElementById(id);el.value=String(val);el.dispatchEvent(new Event(event,{bubbles:true}))},text=id=>document.getElementById(id).textContent;
for(let n=1;n<=50;n++){eq(SYM[0][1](n).toString(),String(n*n),'square');eq(SYM[3][1](n).toString(),Array.from({length:n},(_,i)=>BigInt(i+1)).reduce((a,b)=>a*b,1n).toString(),'factorial');eq(SYM[4][1](n).toString(),String(n*(n+1)/2),'sum');eq(SYM[5][1](n).toString(),String(n*(n+1)*(2*n+1)/6),'sum-square');eq(SYM[6][1](n).toString(),String(Math.floor(Math.log2(n))),'floor-log');}
set('r0_spec_out','1,2,3');r0_specRun();ok(text('r0_spec_out_msg').includes('yasal çıktı değil'),'multiplicity spec');set('r0_spec_out','1,1,2,3');r0_specRun();ok(text('r0_spec_out_msg').includes('yasal çıktı')&&!text('r0_spec_out_msg').includes('değil'),'spec legal');set('r0_spec_in','1,no,2');r0_specRun();ok(text('r0_spec_out_msg').includes('Denetim yapılmadı'),'bad spec');cases.push('symbol definitions, specification/multiplicity/input');
eq(r0_nnTour(0,[-21,-5,-1,1,3,11]).tot,84,'nearest tour84');eq(r0_lineOpt(0,[-21,-5,-1,1,3,11]),64,'tour optimum64');
for(const jobs of Object.values(IV)){let best=0;for(let mask=0;mask<1<<jobs.length;mask++){const chosen=jobs.filter((_,i)=>mask>>i&1);if(chosen.every((a,i)=>chosen.slice(i+1).every(b=>!(a[1]<b[2]&&b[1]<a[2]))))best=Math.max(best,chosen.length)}eq(r0_pickIv(jobs,j=>j[2]).length,best,'interval earliest finish optimum')}eq(r0_knGreedy([6,5,5],10,'large').sum,6,'greedy subset fail');eq(r0_knBrute([6,5,5],10),[5,5],'subset oracle');cases.push('nearest-neighbour, interval scheduling, subset greedy/oracle');
for(let n=1;n<=100;n++){for(const pattern of CTP)eq(pattern.run(n).reduce((a,b)=>a+b,0),pattern.form(n),'statement counter');const a=Array.from({length:n},(_,i)=>i);for(const x of [-1,0,n>>1,n-1,n])eq(r0_search(a,x).c,x<0||x>=n?n:x+1,'linear count')}cases.push('RAM statement counters, best/worst linear search');
for(let n=1;n<=63;n++)for(let o=0;o<5;o++)for(let i=0;i<4;i++){let I=[];if(o<2){for(let v=0;v<n;v+=(o?2:1))I.push(v)}else if(o<4){for(let v=1;v<n;v*=(o===2?2:3))I.push(v)}else{for(let v=n;v>1;v=Math.floor(v/2))I.push(v)}let sum=0;for(const v of I){if(i===0)sum++;else if(i===1)for(let j=0;j<n;j++)sum++;else if(i===2)for(let j=0;j<v;j++)sum++;else for(let j=1;j<n;j*=2)sum++}eq(window.r3_loopCount(o,i,n),sum,`loop ${o}/${i}/${n}`)}cases.push('all20 nested-loop patterns n1–63 independent loop oracle');
for(let n=1;n<=40;n++){set('r3_bin_a',Array.from({length:n},(_,i)=>i).join(','));for(const x of [-1,0,n>>1,n-1,n]){set('r3_bin_x',x);eq(Number(text('r3_bin_res')),x>=0&&x<n?x:-1,'binary result');ok(Number(text('r3_bin_cmp'))<=Math.floor(Math.log2(n))+1,'binary bound')}}set('r3_bin_a','');eq(text('r3_bin_res'),'−1','empty binary');eq(text('r3_bin_cmp'),'0','empty binary counts');cases.push('binary search sizes1–40 found/missing plus empty');
for(const mode of ['sum','max','maxbad','ins','sel'])for(const list of ['4,1,3','-3,-1,-7','2,2,1']){set('r3_inv_m',mode,'change');set('r3_inv_a',list);ok(text('r3_inv_res').includes(mode==='maxbad'&&Math.max(0,...list.split(',').slice(1).map(Number))!==Math.max(...list.split(',').map(Number))?'çıktı yanlış':'çıktı doğru'),'invariant final oracle')}set('r3_inv_a','');ok(text('r3_inv_res').includes('boş olmayan'),'empty invariant clears');set('r3_weak_a','1,1,2');set('r3_weak_b','1,2,2');ok(text('r3_weak_wv').includes('evet')&&text('r3_weak_sv').includes('hayır'),'weak vs multiplicity');cases.push('five invariant variants on negative/duplicate/normal lists, weak vs strong');
set('r3_half_n',1000);document.getElementById('r3_half_a').click();eq(text('r3_half_un'),'10','ceil half');eq(text('r3_half_dn'),'9','floor half');eq(text('r3_half_bn'),'10','doubling');set('r3_pair_a',-1);ok(text('r3_pair_v').includes('pozitif'),'invalid constants');set('r3_flt_s','10,20,30,40,50');set('r3_flt_k1',3);eq(text('r3_flt_o1'),'[20, 30, 40]','filter average');eq(text('r3_flt_c1'),'9','filter operations');set('r3_flt_s','');eq(text('r3_flt_f1'),'0','empty filter');for(let k=1;k<=9;k++){set('r3_flt_k',k);ok(text('r3_flt_same').includes('birebir aynı'),'2D separable filter');eq(Number(text('r3_flt_d').replace(/\D/g,'')),12*16*k*k,'2D direct count');eq(Number(text('r3_flt_s2').replace(/\D/g,'')),2*12*16*k,'2D separable count')}cases.push('halving/floor/ceiling, positive constants, 1D/2D filtering k1–9');
return {assertions,failures,cases}});results.push({route:'w3',...r,errors:p.errors});await p.close();
p=await load('w4');r=await p.evaluate(()=>{const failures=[],cases=[];let assertions=0;const ok=(v,msg)=>{assertions++;if(!v)failures.push(msg)},eq=(a,b,msg)=>ok(JSON.stringify(a)===JSON.stringify(b),msg),click=id=>document.getElementById(id).click(),set=(id,val,event='input')=>{const e=document.getElementById(id);e.value=String(val);e.dispatchEvent(new Event(event,{bubbles:true}))},text=id=>document.getElementById(id).textContent;
for(let n=1;n<=32;n++){for(let i=0;i<=n;i++){const a=Array.from({length:n},(_,j)=>j),expected=a.slice();expected.splice(i,0,99);eq(insArr(a,i,99),n-i,'array insert moves');eq(a,expected,'array inserted')}for(let i=0;i<n;i++){const a=Array.from({length:n},(_,j)=>j),expected=a.filter((_,j)=>j!==i);eq(delArr(a,i),n-i-1,'array delete moves');eq(a,expected,'array deleted')}}cases.push('array shifts at every position n1–32');
for(const a of [[],[1],[1,2,3,4],[2,2,3]])for(const op of ['front','after','del','find','rev'])for(const target of [1,2,99]){const steps=llSim(a,op,9,target),last=steps.at(-1),expected=a.slice();if(op==='front')expected.unshift(9);if(op==='after'&&expected.includes(target))expected.splice(expected.indexOf(target)+1,0,9);if(op==='del'&&expected.includes(target))expected.splice(expected.indexOf(target),1);if(op==='rev')expected.reverse();eq(llWalk(last.S),expected,'linked list final structure');if(op==='rev')eq(last.vis,a.length,'reverse traversal count')}cases.push('linked-list five operations on empty/singleton/duplicates/missing keys');
for(const c of [1,4,10])for(let n=1;n<=128;n++){const d=daSim('dbl',c,n);let capacity=c,copies=0;while(capacity<n){copies+=capacity;capacity*=2}eq(d.copies,copies,'dynamic copy count');eq(d.total,n+copies,'dynamic total');ok(d.total<3*n,'dynamic bound')}set('da_c',2.5,'change');eq(DA.cap,2,'fractional capacity integer');cases.push('dynamic-array copies/total across capacities1/4/10 and n1–128');
for(const [s,v] of [['','res'],['{[()]}',true],['([)]',false],['(()',false],['x < y',true]]){const last=pbSteps(s).at(-1);if(v!=='res')eq(last.end,v,'parentheses '+s)}eq(pfSteps('5 1 2 + 4 * + 3 -').at(-1).res,14,'postfix');eq(pfSteps('8 2 /').at(-1).res,4,'division order');ok(pfSteps('1 0 /').at(-1).err,'zero division');ok(pfSteps('1 +').at(-1).err,'stack underflow');for(const s of ['3+','(3+4','3+4)','x3+4','3 4','-3+4','3**4','()'])ok(shunt(s).err,'infix rejects '+s);eq(shunt('3+4*2-(1+2)').out,['3','4','2','*','+','1','2','+','-'],'shunting-yard');cases.push('parentheses, postfix order/errors, strict infix grammar/precedence');
click('mn_ex');eq(MN.m,[5,3,3],'minimum stack');click('mn_pop');eq(MN.m,[5,3],'minimum stack pop');click('mn_pop');eq(MN.m,[5],'minimum stack pop again');click('mn_r');set('mn_v','');click('mn_push');eq(MN.a,[],'min stack empty input');cases.push('min stack repeated minima and empty input');
rbReset(3);for(let i=0;i<4;i++)click('rb_push');eq(RB.count,3,'ring reject full');eq(RB.next,4,'ring reject keeps sequence');set('rb_pol','ovr','change');click('rb_push');eq(Array.from({length:RB.count},(_,i)=>RB.buf[(RB.head+i)%RB.N]),[2,3,4],'ring overwrite FIFO');click('rb_pop');eq(Array.from({length:RB.count},(_,i)=>RB.buf[(RB.head+i)%RB.N]),[3,4],'ring dequeue');cases.push('ring wrap/full reject/overwrite/FIFO');
tqReset();for(let i=0;i<4;i++)tqEnq();eq([tqDeq(),tqDeq(),tqDeq(),tqDeq()],[1,2,3,4],'two-stack queue');eq(TQ.units,16,'two-stack total4n');cases.push('two-stack queue order and amortized counter');eq(gsSim('queue').at(-1).vis,['A','B','C','D','E','F'],'BFS order');eq(gsSim('stack').at(-1).vis,['A','C','F','E','B','D'],'DFS order');ok(text('mm_t').includes('518'),'memory full bookkeeping');set('mm_n',-1);ok(text('mm_t').includes('negatif olmayan'),'negative memory rejected');set('mm_n',256);cases.push('DFS/BFS and memory bookkeeping');
maReset();for(let i=0;i<30;i++){maStep();const w=MA.hist.slice(-MA.W);eq(MA.sum,w.reduce((a,b)=>a+b,0),'moving average rolling sum');if(i===0)ok(text('ma_out').includes('1 işlem'),'moving avg startup exact counter');if(i===4)ok(text('ma_out').includes('2 işlem'),'moving avg full exact counter')}cases.push('moving average30 samples vs independent sum');return {assertions,failures,cases}});results.push({route:'w4',...r,errors:p.errors});await p.close();
p=await load('w5');r=await p.evaluate(()=>{const failures=[],cases=[];let assertions=0;const ok=(v,msg)=>{assertions++;if(!v)failures.push(msg)},eq=(a,b,msg)=>ok(JSON.stringify(a)===JSON.stringify(b),msg),set=(id,val,event='input')=>{const el=document.getElementById(id);el.value=String(val);el.dispatchEvent(new Event(event,{bubbles:true}))},text=id=>document.getElementById(id).textContent;
for(const order of [[2,1,7,4,3,6,5,8],[50,30,70,20,40,60,80],[1,2,3,4,5]]){const sorted=order.slice().sort((a,b)=>a-b),tree=build(order);eq(inorder(tree),sorted,'BST inorder');ok(vbCheck(tree).inc,'BST invariant');for(let i=0;i<sorted.length;i++){eq(succOf(tree,sorted[i],1).node?.k??null,sorted[i+1]??null,'successor');eq(succOf(tree,sorted[i],-1).node?.k??null,sorted[i-1]??null,'predecessor')}for(const key of [...order,99]){const d=delSteps(tree,key);eq(inorder(d.tree),sorted.filter(x=>x!==key),'BST deletion');ok(vbCheck(d.tree).inc,'BST ordering after deletion')}}ok(vbCheck(VB[1]()).local.length===0&&vbCheck(VB[1]()).glob.length>0,'global bounds trap');set('bt_x',2.5);btRun('ins');ok(text('bt_note').includes('tamsayı'),'BST rejects fractional');cases.push('BST traversal, full successor/predecessor oracle, all deletion cases including absent, global bounds');
for(const n of [1,2,3,4,15,63]){const a=Array.from({length:n},(_,i)=>i),m=[];medOrder(0,n-1,m);eq(bstStats(a).h,n-1,'chain height');eq(bstStats(m).h,Math.floor(Math.log2(n)),'median height')}cases.push('chain and balanced heights');
h2preset(7,'lin','tomb',[["ins",7],["ins",14],["ins",21]]);h2do('del',14);let frames=h2do('ins',21);eq(H2.n,2,'no duplicate beyond tombstone');eq(frames.at(-1).probes,3,'duplicate probes counted');frames=h2do('ins',28);eq(H2.cells[1],28,'reuse first tombstone');eq(frames.at(-1).probes,4,'all insertion probes counted');eq(h2find(21).found,true,'search beyond tombstone');h2preset(7,'lin','naive',[["ins",7],["ins",14],["ins",21],["del",14],["srch",21]]);eq(h2find(21).found,false,'demonstrated naive deletion failure');h2preset(5,'chain','tomb',[["ins",10],["ins",15],["ins",3],["ins",20]]);eq(H2.n,4,'chain size');eq(H2.cells[0],[10,15,20],'chain collision list');h2do('del',15);eq(H2.cells[0],[10,20],'chain delete');cases.push('hash insertion/search/delete, duplicate beyond tombstone, true probe counts, intentional bad deletion, chaining');
for(const n of [0,1,2,23,50,365,366]){let p=1;for(let i=0;i<n;i++)p*=Math.max(0,(365-i)/365);ok(Math.abs(bdP(n,365)-(1-p))<1e-12,'birthday probability')}cases.push('birthday exact product through pigeonhole');
for(const s of ['Ali','😀A','<b>','ı','a'.repeat(20)]){set('sh_s',s);ok(text('sh_out').includes('iki hesap aynı'),'hash exact BigInt vs rolling');ok(!document.querySelector('#sh_out b b'),'hash text markup escaped')}set('an_in','dog god cat act <b>');ok(text('an_out').includes('<b>'),'anagram escaped');ok(!document.querySelector('#an_out b b'),'anagram no injected markup');cases.push('string polynomial hash Unicode/typed markup, anagram grouping');
for(let n=0;n<=7;n++)for(let mask=0;mask<3**n;mask++){if(mask%17!==0&&n>4)continue;let q=mask,a=Array.from({length:n},()=>{const x=q%3-1;q=Math.floor(q/3);return x});for(const T of [-2,0,2]){set('ts_a',a.join(','));set('ts_t',T);let bf=false;for(let i=0;i<n;i++)for(let j=i+1;j<n;j++)bf ||= a[i]+a[j]===T;ok(text('ts_out').includes('üç yöntem aynı'),'two sum methods vs oracle');ok(text('ts_out').includes(bf?'çift) kontrolü: var':'çift) kontrolü: yok'),'two sum truth')}}set('ts_a','1,bad,2');ok(text('ts_out').includes('geçerli'),'two sum invalid list');cases.push('two-sum small negative/duplicate lists and malformed input');
for(const [t,p] of [['ABRACADABRA','ABRA'],['😀a😀a','😀a'],['a😀b','😀b'],['😀😀😀','😀😀'],['a<b>a<b>','<b>'],['AAAAA','AAA'],['abc','z']])for(const q of [2,101]){set('rk_t',t);set('rk_p',p);set('rk_q',q);const T=Array.from(t),P=Array.from(p);let z=0;for(let i=0;i+P.length<=T.length;i++)if(T.slice(i,i+P.length).join('')===p)z++;ok(text('rk_out').includes(`gerçek eşleşme ${z}`),'Rabin-Karp matches '+t);ok(text('rk_out').includes('her satırda: ✓'),'rolling = direct '+t);ok(!document.querySelector('#rk_tb td b'),'window markup escaped')}cases.push('Rabin–Karp ASCII/Unicode/markup/repeated/missing with small and normal moduli');
for(const [input,valid] of [['0x100,0x120,0x140,0x121',true],['0,2047',true],['2048',false],['2.5',false],['1,1',false],['-1',false],['',false],['0x1g',false]]){set('cn_ids',input);ok(valid?!text('cn_out').includes('farklı 11 bit'):text('cn_out').includes('farklı 11 bit'),'CAN validation '+input)}set('cn_ids','0x100,0x120,0x140,0x121');document.getElementById('cn_best').click();eq(Number(document.getElementById('cn_m').value),5,'CAN best modulus');for(let m=2;m<=64;m++){const ids=[256,288,320,289],r=cnSim(ids,m);if(!r.full)for(let i=0;i<ids.length;i++){let p=ids[i]%m,c=1;while(r.t[p]!==ids[i]&&c<=m){p=(p+1)%m;c++}eq(r.pr[i],c,'CAN search probe oracle')}}cases.push('11bit CAN domain/duplicates/errors and all moduli2–64 probes');return {assertions,failures,cases}});results.push({route:'w5',...r,errors:p.errors});await p.close();
for(const route of ['w1','w2','w3/tekrar','w3/ek-notlar','w4/ek-notlar','w5/ek-notlar']){p=await load(route);results.push({route,errors:p.errors,loadOnly:true});await p.close()}
if(process.env.AA_REPORT_DIR){fs.mkdirSync(process.env.AA_REPORT_DIR,{recursive:true});fs.writeFileSync(process.env.AA_REPORT_DIR+'/main-widget-oracles.json',JSON.stringify(results,null,2))}console.log(results.map(x=>({route:x.route,assertions:x.assertions,failures:x.failures,errors:x.errors})));await b.close();if(results.some(x=>x.errors.length||x.failures?.length))process.exitCode=1})().catch(e=>{console.error(e);process.exitCode=1});
