/* Browser checks against production lesson helpers and independent small-instance oracles.
 * Serve the repository and pass its AA URL as the first argument; requires Playwright. */
const base=(process.argv[2]||'http://127.0.0.1:8873/courses/aa').replace(/\/$/,'');
const reportFile=process.argv[3]||require('path').join(require('os').tmpdir(),'simple-w6-w10.json');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs=require('fs');
const BASE=base;
(async()=>{const b=await chromium.launch({headless:true});const results=[];
for(let week=6;week<=10;week++){const p=await b.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(BASE+'/w'+week+'/');
 const r=await p.evaluate(week=>{let seed=374;const rnd=()=>{seed=(1664525*seed+1013904223)>>>0;return seed/4294967296};const ri=n=>Math.floor(rnd()*n);const arr=n=>Array.from({length:n},()=>ri(31)-15);let assertions=0,cases=0;
 const ok=(cond,msg)=>{assertions++;if(!cond)throw Error(msg)};const eq=(a,b)=>JSON.stringify(a)===JSON.stringify(b);const sort=a=>[...a].sort((a,b)=>a-b);
 if(week===6){ok(finiteMean(1e308,1e308)===1e308,'overflow-safe median');ok(finiteMean(5e-324,5e-324)===5e-324,'subnormal median');ok(finiteMean(-1e308,1e308)===0,'opposite extreme median');for(let t=0;t<150;t++){cases++;const a=arr(ri(65));for(const mx of [false,true]){const h=leanHeapify(a,mx),v=leanInsertAll(a,mx);for(const q of [h.h,v.h]){ok(eq(sort(q),sort(a)),'heap permutation');ok(q.every((x,i)=>i===0||(mx?q[(i-1)>>1]>=x:q[(i-1)>>1]<=x)),'heap invariant')}ok(h.c<2*a.length||a.length===0,'linear heap comparisons')}
 ok(eq(leanHeapsort(a).a,sort(a)),'heapsort');const q=new PQ((a,b)=>a<b);a.forEach(x=>q.push(x));const out=[];while(q.n)out.push(q.pop());ok(eq(out,sort(a)),'PQ extract order')}}
 if(week===7){for(let t=0;t<150;t++){cases++;const a=arr(ri(35));const expected=sort(a);for(const rule of ['last','first','mid','med3','rand'])ok(eq(qsRun(a,rule).a,expected),'quicksort '+rule);ok(eq(msC(a).out,expected),'mergesort');ok(eq(heapC(a).a,expected),'heapsort');const i=ri(a.length+1),L=sort(a.slice(0,i)),R=sort(a.slice(i)),m=mergeC(L,R);ok(eq(m.out,expected),'merge');ok(m.c<=Math.max(0,a.length-1),'merge upper bound');ok(m.c>=Math.min(L.length,R.length),'merge lower bound');ok(qs3(Array(ri(20)+2).fill(1))%2===0,'3-way equality comparison counter')}
 const equalN=12;ok(qs3(Array(equalN).fill(7))===2*(equalN-1),'threeway counts both primitive comparisons');ok(Wms(8)===17,'merge worst exact')}
 if(week===8){for(let t=0;t<120;t++){cases++;const n=ri(8)+2,E=[],dir=t%2===0;for(let i=1;i<=n;i++)for(let j=dir?1:i+1;j<=n;j++)if(i!==j&&rnd()<.25)E.push([i,j]);const g=mkG(n,E,dir),D=Array.from({length:n+1},(_,i)=>Array.from({length:n+1},(_,j)=>i===j?0:Infinity));E.forEach(([a,b])=>{D[a][b]=1;if(!dir)D[b][a]=1});for(let k=1;k<=n;k++)for(let i=1;i<=n;i++)for(let j=1;j<=n;j++)D[i][j]=Math.min(D[i][j],D[i][k]+D[k][j]);const s=ri(n)+1,r=bfsLean(g,s);for(let v=1;v<=n;v++){ok(r.dist[v]===(D[s][v]===Infinity?null:D[s][v]),'BFS Floyd distance');if(r.par[v]!==null)ok(g.adj[r.par[v]].includes(v)&&r.dist[v]===r.dist[r.par[v]]+1,'BFS parent')}
 if(!dir){let bip=false;for(let mask=0;mask<(1<<n);mask++)if(E.every(([a,b])=>((mask>>(a-1))&1)!==((mask>>(b-1))&1))){bip=true;break}const z=bpEvents(g);ok(!z.bad===bip,'bipartite brute color');if(z.bad){const cycle=oddCycle(z.par,z.bad[0],z.bad[1]);ok(cycle.length%2===1,'odd cycle parity')}}}}
 if(week===9){for(let t=0;t<120;t++){cases++;const n=ri(6)+2,V=Array.from({length:n},(_,i)=>String.fromCharCode(65+i)),E=[];for(let i=0;i<n;i++)for(let j=0;j<n;j++)if(rnd()<.2)E.push([V[i],V[j]]);const g=mkGraph(V.join(',')+','+E.map(e=>e.join('→')).join(','),true);const D=Array.from({length:n},(_,i)=>Array.from({length:n},(_,j)=>i===j));E.forEach(([a,b])=>D[V.indexOf(a)][V.indexOf(b)]=true);for(let k=0;k<n;k++)for(let i=0;i<n;i++)for(let j=0;j<n;j++)D[i][j]||=D[i][k]&&D[k][j];const cyc=E.some(([a,b])=>D[V.indexOf(b)][V.indexOf(a)]),R=dfsRun(g,V[0]),K=kahn(g);ok(!!R.back.length===cyc,'DFS cycle');ok(!K.ok===cyc,'Kahn cycle');const norm=c=>c.map(a=>[...a].sort().join('')).sort();const seen=new Set(),groups=[];for(let i=0;i<n;i++)if(!seen.has(i)){const c=V.filter((_,j)=>D[i][j]&&D[j][i]);c.forEach(v=>seen.add(V.indexOf(v)));groups.push(c)}ok(eq(norm(sccKos(g).comps),norm(groups)),'SCC closure');let num=0;function permutations(prefix,rest){if(!rest.length){if(E.every(([a,b])=>prefix.indexOf(a)<prefix.indexOf(b)))num++;return}for(const v of rest)permutations([...prefix,v],rest.filter(x=>x!==v))}permutations([],V);ok(countTopo(g)===num,'topological exhaustive count');
 const U=mkGraph(V.join(',')+','+E.filter(([a,b])=>a!==b).map(e=>e.join('-')).join(','),false);const count=skip=>{const unseen=new Set(V.filter(v=>v!==skip));let c=0;while(unseen.size){c++;const q=[unseen.values().next().value];unseen.delete(q[0]);while(q.length)for(const v of U.adj[q.pop()])if(unseen.has(v)){unseen.delete(v);q.push(v)}}return c};const base=count(null),ap=V.filter(v=>count(v)>base);ok(eq([...articulation(U).ap].sort(),ap.sort()),'articulation brute removal');ok(Object.values(R.entry).every((x,i)=>x<R.exit[Object.keys(R.entry)[i]])&&R.clock===2*n,'DFS clock')}
 ok(!!mkGraph('__proto__→A',true).err,'reserved graph label guard');ok(!!mkGraph('<b>A</b>→B',true).err,'HTML graph label guard')}
 if(week===10){for(let t=0;t<100;t++){cases++;const n=ri(5)+2,E=[],seen=new Set();for(let i=1;i<n;i++){let a=ri(i);E.push([a,i,ri(15)-5]);seen.add(a+','+i)}for(let i=0;i<n;i++)for(let j=i+1;j<n;j++)if(!seen.has(i+','+j)&&rnd()<.35&&E.length<12)E.push([i,j,ri(15)-5]);const g={n,E,names:Array.from({length:n},(_,i)=>String(i))};let best=Infinity,count=0;function choose(start,list){if(list.length===n-1){const adj=Array.from({length:n},()=>[]);let cost=0;for(const i of list){const [a,b,w]=E[i];adj[a].push(b);adj[b].push(a);cost+=w}const seen=new Set([0]),q=[0];while(q.length)for(const v of adj[q.pop()])if(!seen.has(v)){seen.add(v);q.push(v)}if(seen.size===n){best=Math.min(best,cost);count++}return}for(let i=start;i<E.length;i++)choose(i+1,[...list,i])}choose(0,[]);ok(kruskalTrace(g).total===best,'Kruskal brute optimum');for(let s=0;s<n;s++){const P=primTrace(g,s);ok(P.connected&&P.total===best,'Prim brute optimum start '+s)}ok(enumTrees(g).cnt===count,'tree enumeration count');
 const u=mkUF(n),labels=Array.from({length:n},(_,i)=>i);for(let k=0;k<40;k++){const a=ri(n),b=ri(n),la=labels[a],lb=labels[b];ufUnion(u,a,b,!!(t%2),!!(t%3));for(let i=0;i<n;i++)if(labels[i]===lb)labels[i]=la;for(let i=0;i<n;i++)for(let j=0;j<n;j++)ok((ufRoot(u,i)===ufRoot(u,j))===(labels[i]===labels[j]),'UF partition')}}}
 return{cases,assertions};},week);if(errors.length)throw Error('Week '+week+' page errors: '+errors.join('; '));results.push({week,...r,errors});await p.close()}
fs.writeFileSync(reportFile,JSON.stringify(results,null,2));console.log(results);await b.close();if(results.some(x=>x.errors.length))process.exitCode=1})().catch(e=>{console.error(e);process.exit(1)});
