"""Canonical 14-week topic sequence. Lecture numbers refer to the supplied bilingual notes.

Each week is a dict:
  title, lectures, summary, python            – as before
  examples  – list of worked examples: {question, example, steps, edge, label?, figure?}
              figure: an int selects visuals.figure(key); a string is inline HTML; absent = no figure
  objectives – 3–5 measurable statements ("By the end of this week you can…")
  scope      – examinable topics; "(reading only)" marks material that is read but not examined
  code       – optional: an int selects visuals.CODES[key]; a string is the Python demonstration itself
Helpers `title(n)`, `lectures(n)` and `WEEK_TUPLES` keep older callers working.
"""

def ex(question,example,steps,edge,label=None,figure=None):
 d={'question':question,'example':example,'steps':steps,'edge':edge}
 if label:d['label']=label
 if figure is not None:d['figure']=figure
 return d

WEEKS=[
{'title':'Algorithms and correctness','lectures':[1],
 'summary':'Specify the answer, trace a method, and challenge a tempting rule. Robot tours and interval scheduling show why correctness needs an argument.',
 'objectives':['State a problem as an input contract and an output contract before choosing a method.','Trace a greedy rule on a small instance and record every choice it makes.','Refute a claimed rule with one counterexample, and explain why one is enough.','Explain the three parts of an induction argument for correctness.'],
 'scope':['Problem, instance, algorithm, correctness','Robot tour: nearest-neighbour and closest-pair counterexamples','Interval scheduling by earliest finish, and why it is correct','Counterexamples: small, extreme and tied inputs','Induction as a correctness argument (structure only)'],
 'examples':[ex('Can a locally attractive choice give a globally bad answer?',
 'Jobs A=[0,3], B=[2,4], C=[3,5]. Choose the largest compatible set; touching endpoints are allowed.',
 ['Sort by finish time: A, B, C.','Accept A, ending at 3. Reject B because it starts at 2.','Accept C because it starts at 3. Result: two jobs.','The earliest finish leaves at least as much room as any competing first choice. Repeating this exchange establishes optimality for equal-value fixed intervals.'],
 'If jobs have different fees, maximising their count may not maximise income. We return to this distinction in dynamic programming.',figure=1)],
 'python':'Variables name values; assignment stores a result. An algorithm can be explained before any Python is written.'},
{'title':'Counting work and growth','lectures':[2],
 'summary':'Count a chosen basic operation, distinguish input cases, and use O, Ω and Θ to describe growth. Timing is supporting evidence, not a proof.',
 'objectives':['Count a named basic operation for a small input under the RAM model.','Distinguish best, worst and average case for one input size.','Prove an O, Ω or Θ bound from the definition by choosing constants c and n₀.','Compare two growth classes and say which dominates for large n.'],
 'scope':['RAM model and what counts as one step','Best, worst and average case','Definitions of O, Ω, Θ with constants c and n₀','Worked bounds for polynomials such as 3n² − 100n + 6','Sum and product rules for Big-O','Knapsack warm-up: greedy rules and their counterexamples (reading only)'],
 'examples':[ex('What changes when the input doubles?',
 'A procedure performs T(n)=3n²+10n basic operations. Give a tight asymptotic bound.',
 ['For n≥1, 10n≤10n², so T(n)≤13n². This proves O(n²).','Also T(n)≥3n² for n≥1, proving Ω(n²).','Together these bounds give Θ(n²). Constants do not change the growth class.','Doubling n gives a ratio approaching 4, not exactly 4 at every finite n.'],
 'An O(n³) upper bound is also true but less informative. Big-O does not itself mean worst case; first specify which cost function is being bounded.',figure=2)],
 'python':'Read n*n as n². Use arithmetic to check a small case; no plotting code is required.'},
{'title':'Program analysis and logarithms','lectures':[3],
 'summary':'Trace simple and nested loops, derive sums, and compare selection with insertion sort. Repeated halving explains logarithmic work.',
 'objectives':['Derive the exact count and the Θ class of a nested loop from its bounds.','Trace selection sort and insertion sort on five keys and count comparisons.','Bound the running time of a loop nest using the product rule.','Explain why repeated halving takes about log₂n steps, and use log rules to simplify bounds.'],
 'scope':['Multiplying Big-O bounds; nested loops','Selection sort and insertion sort: traces, best and worst case','Triangular sums 1+2+…+n and their Θ class','Asymptotic dominance table: which class wins for large n','Logarithms: halving, binary search, log rules, change of base'],
 'examples':[ex('When do we add counts, and when do we multiply them?',
 'An outer loop uses i=1,…,n. For each i, the inner loop performs i comparisons.',
 ['For n=4 the row counts are 1,2,3,4, totalling 10.','In general T(n)=1+2+…+n=n(n+1)/2.','The dominant term is n²/2, giving Θ(n²).','By contrast, repeatedly halving n until 1 takes about log₂n steps.'],
 'Two consecutive n-step loops give 2n, not n². Multiplication applies when one complete loop is repeated inside another.',figure=3)],
 'python':'for i in range(1,n+1) visits 1 through n. Indentation shows which instructions repeat together.'},
{'title':'Arrays, linked lists, stacks and queues','lectures':[4],
 'summary':'Compare data structures by the operations they support. Draw storage, links, and the order in which items leave.',
 'objectives':['Compare arrays and linked lists by the cost of access, insertion and deletion.','Trace a stack and a queue on the same arrivals and state which item leaves next.','Choose a container for a stated workload and justify the choice by its dominant operation.','Bound the cost of front insertion in a packed array and in a linked list.'],
 'scope':['Contiguous versus linked storage','Arrays: constant-time indexing, shifting cost, resizing','Singly linked lists: search, insert, delete with a known node','Stacks (LIFO) and queues (FIFO)','The dictionary operations and their array/list costs'],
 'examples':[ex('Which operation does the problem need to be cheap?',
 'Insert 8 at the front of the packed array [2,5,7]. Then compare a singly linked list with a known head.',
 ['The array must move 7,5,2 one position right before storing 8: three moves.','For n existing items, this front insertion is Θ(n), assuming enough capacity.','For a linked list, create a node pointing to the old head, then update the head: O(1).','The tradeoff reverses for arbitrary indexed access: array O(1), linked-list traversal O(n).'],
 'Linked-list insertion is constant time only when the necessary location/link is already known. Finding it may require a full search.',figure=4)],
 'python':'A Python list behaves like a dynamic array, not a linked list. A stack is last-in first-out; a queue is first-in first-out.'},
{'title':'Search trees and hashing','lectures':[5,6],
 'summary':'Use trees and hash tables to implement dictionaries. Relate tree height, collisions and load factor to the actual search cost.',
 'objectives':['Trace search, insertion and the three deletion cases in a binary search tree.','Relate the height of a search tree to its worst-case search cost.','Trace hashing with chaining and with linear probing, including a lookup after deletion.','Compare expected and worst-case dictionary costs and state the assumptions behind each.'],
 'scope':['Binary search trees: search, min/max, successor, in-order traversal, insert, delete','Height and balance: why the log appears','Hash tables: hash functions, chaining, open addressing with linear probing','Load factor and expected cost; the birthday paradox as motivation','Rabin–Karp string matching (reading only)'],
 'examples':[ex('What assumptions make a lookup fast?',
 'Insert 10,15,3,20 into five hash slots using h(k)=k mod 5 and linear probing.',
 ['10 enters slot 0.','15 also hashes to 0; slot 1 is the first free slot.','3 enters slot 3.','20 probes 0,1,2 and enters slot 2. A lookup must use the same probing rule.'],
 'Deleting 10 by making slot 0 look never-used can break a later search for 20. Use a tombstone or a correct repair scheme. Expected constant lookup is conditional, not a worst-case guarantee.',figure=5)],
 'python':'A dictionary stores key–value pairs. Python dict syntax is a demonstration; draw the slots before running code.'},
{'title':'Priority queues and heaps','lectures':[7],
 'summary':'Maintain a partial order that makes the next minimum or maximum easy to remove. Separate one heap operation from building a whole heap.',
 'objectives':['Trace insert (bubble up) and extract-min (bubble down) on an array-stored heap.','Derive the O(log n) bound for one heap operation from the tree height.','Explain why building a heap bottom-up costs O(n) although n insertions cost O(n log n).','Trace heapsort and bound its worst-case running time.'],
 'scope':['Why sorting matters; what sorting makes easy','Priority queue operations and array implementations','Heaps: shape and order properties, parent/child indexing from position 1','Insert, extract-min, build-heap in linear time','Heapsort: trace and O(n log n) worst case'],
 'examples':[ex('Why does a heap avoid searching every item for the next minimum?',
 'Insert 1 into the min-heap [2,4,3], using array positions starting at 1.',
 ['Append 1 at position 4: [2,4,3,1].','Compare with its parent at position 2; swap: [2,1,3,4].','Compare with the root; swap: [1,2,3,4].','There are at most O(log n) levels. Bottom-up construction of an entire heap is O(n), because most nodes have very small height.'],
 'A heap is not a fully sorted array. Its root is extreme; siblings need not be ordered. Heapsort is O(n log n) in the worst case.',figure=6)],
 'python':'Parent index is i//2 with 1-based positions. Python uses 0-based lists, so keep the convention explicit.'},
{'title':'Sorting II: mergesort, quicksort, lower bounds, linear sorting — and solving recurrences','lectures':[8,9],
 'summary':'Split problems into smaller parts and trace how the results combine. Solve the recurrences that describe them, explain the comparison lower bound, and see how restricted integer keys permit linear sorting.',
 'objectives':['Trace merge and partition on small arrays and count the key comparisons.','Derive the mergesort recurrence and solve it with a recursion tree or the master theorem.','Compare quicksort’s best, worst and expected cases and say what a random pivot guarantees.','Prove the Ω(n log n) comparison lower bound from the decision tree.','Trace bucketsort and radix sort and state the assumptions that make them linear.'],
 'scope':['Mergesort: trace, recurrence T(n)=2T(n/2)+Θ(n), Θ(n log n)','Solving recurrences: recursion trees and the master theorem (core)','Quicksort: partition, pivot choice, worst case Θ(n²), expected O(n log n) with random pivots','Decision-tree lower bound Ω(n log n) for comparison sorting','Bucketsort and LSD radix sort: stability, cost O(d(n+b)), assumptions','Is quicksort really faster than heapsort? (reading only)'],
 'examples':[ex('Where does n log n come from?',
 'Merge the sorted runs [1,4,7] and [2,3,8].',
 ['Compare the front values: choose 1, then 2, then 3.','Compare 4 with 8: choose 4. Compare 7 with 8: choose 7.','The first run is empty; append 8 without another key comparison. Five comparisons merge six items.','Mergesort handles n items per level across about log₂n levels: Θ(n log n).'],
 'Quicksort can split into sizes 0 and n−1 repeatedly, giving Θ(n²). Random pivots give an expected O(n log n) bound, not a worst-case guarantee.',figure=7),
 ex('How can a linear-time sort coexist with an n log n lower bound?',
 'Stable radix-sort [21,13,12,23] by units, then tens.',
 ['Units pass: [21,12,13,23]. Equal units preserve input order.','Tens pass: [12,13,21,23]. Equal tens preserve the units order established earlier.','Each stable counting pass costs O(n+b) for base b. With d digits the total is O(d(n+b)).','The Ω(n log n) worst-case lower bound concerns comparison-only sorting of arbitrary distinct keys. Radix sort uses key digits.'],
 'The digit count and range matter. Calling radix sort O(n) without stating these assumptions is incomplete.',figure=8)],
 'python':'A recursive function calls itself on a smaller input and must have a stopping case. Trace the calls as a tree first. Use // for integer quotient and % for remainder to isolate a digit.',
 'code':'def merge(a, b):\n    out = []\n    i = j = 0\n    while i < len(a) and j < len(b):\n        if a[i] <= b[j]:\n            out.append(a[i]); i += 1\n        else:\n            out.append(b[j]); j += 1\n    return out + a[i:] + b[j:]\nprint(merge([1, 4, 7], [2, 3, 8]))  # [1, 2, 3, 4, 7, 8]\n\nvalues = [21, 13, 12, 23]\n# sorted is stable; these lines demonstrate digit order,\n# not a linear-time counting-sort implementation.\nvalues = sorted(values, key=lambda x: x % 10)\nprint(values)  # [21, 12, 13, 23]\nvalues = sorted(values, key=lambda x: x // 10)\nprint(values)  # [12, 13, 21, 23]'},
{'title':'Graphs I: representations, BFS and its applications','lectures':[10,11],
 'summary':'Represent networks with adjacency lists or matrices. Use a queue to discover vertices in increasing number of edges from the start.',
 'objectives':['Choose between an adjacency matrix and adjacency lists for a stated graph and justify the choice by space and edge-scan cost.','Trace BFS on a small graph, recording discovery order, parents and distances.','Prove that BFS tree paths are shortest paths in an unweighted graph.','Apply BFS to count connected components and to two-colour a graph.'],
 'scope':['Graph vocabulary: directed/undirected, weighted, degree, path, cycle, connected','Adjacency matrix versus adjacency lists: space and operation costs','BFS: queue, discovered/processed states, parent array, O(n+m)','BFS tree and shortest unweighted paths','Applications: connected components, bipartite two-colouring','The adjacency-list record layout used in the notes (reading only)'],
 'examples':[ex('Why does BFS find the shortest unweighted path?',
 'Undirected edges: 1–2,1–3,2–4,3–4,4–5. Run BFS from 1, considering neighbours in increasing order.',
 ['Start with distance(1)=0 and queue [1].','Process 1: discover 2 and 3 at distance 1; queue [2,3].','Process 2: discover 4 at distance 2. Processing 3 does not rediscover 4.','Process 4: discover 5 at distance 3. Discovery order is 1,2,3,4,5; one shortest path is 1–2–4–5.'],
 'BFS minimises edge count; arbitrary edge weights need a different algorithm. Mark vertices when enqueued to avoid repeated insertion.',figure=9)],
 'python':'A dictionary of neighbour lists represents a graph. A deque supports efficient queue removal from the front.','code':9},
{'title':'Graphs II: DFS, edge types, topological order, strongly connected components','lectures':[12],
 'summary':'Trace depth-first search with entry and exit times, classify every edge, and use the classes to detect cycles, order a DAG and find strongly connected components.',
 'objectives':['Trace DFS on a directed graph and record entry and exit times for every vertex.','Classify each edge as tree, back, forward or cross from the times and the vertex states.','Prove that a directed graph has a cycle if and only if DFS meets a back edge.','Derive a topological order from DFS finishing times and check it against every edge.','Compare the DFS and in-degree-removal methods for topological sorting.'],
 'scope':['DFS: recursion, entry/exit times, O(n+m)','Edge types in undirected and directed DFS','Cycle detection by back edges','Topological sorting: reverse finishing order and in-degree-zero removal','Strongly connected components: definition and DFS-based idea','Articulation vertices (reading only)'],
 'examples':[ex('Which edges does DFS turn into tree edges, and what do the others tell us?',
 'Directed edges: A→B, A→C, B→D, C→D, C→F, D→E, E→B. Run DFS from A, taking neighbours in alphabetical order. Classify every edge, then give a topological order or show the cycle.',
 ['Start at A (entry 1). Take the first neighbour B (entry 2), then D (entry 3), then E (entry 4). Tree edges so far: A→B, B→D, D→E.','From E, the edge E→B reaches a vertex that is discovered but not finished: B is still on the recursion stack. Classify E→B as a back edge. Then E finishes (exit 5), D finishes (exit 6) and B finishes (exit 7).','Back at A, take C (entry 8). The edge C→D reaches a finished vertex whose entry time 3 is earlier than 8: a cross edge. The edge C→F opens F (entry 9, exit 10). C finishes at 11 and A at 12.','Result: tree edges A→B, B→D, D→E, A→C, C→F; back edge E→B; cross edge C→D; no forward edge. A back edge closes a directed cycle, here B→D→E→B, so no topological order exists.'],
 'Reverse the edge E→B to B→E. DFS now meets no back edge; B→E becomes a forward edge because E is finished and was entered after B. The finishing order is E, D, B, F, C, A. Reversed, it gives the topological order A, C, F, B, D, E. Check every edge: each points from left to right.',
 figure='dfs')],
 'python':'DFS uses recursion or an explicit stack. Record the entry and exit times in two dictionaries and classify an edge by the state of the vertex it reaches.',
 'code':'g = {"A":["B","C"], "B":["D"], "C":["D","F"], "D":["E"], "E":["B"], "F":[]}\nentry, exit, clock = {}, {}, [0]\ndef dfs(u):\n    clock[0] += 1; entry[u] = clock[0]\n    for v in g[u]:\n        if v not in entry:\n            dfs(v)                      # tree edge\n        elif v not in exit:\n            print("back edge", u, v)     # v still on the stack: a cycle\n    clock[0] += 1; exit[u] = clock[0]\ndfs("A")\nprint(sorted(exit, key=exit.get, reverse=True))  # reverse finishing order'},
{'title':'Minimum spanning trees and union-find','lectures':[13],
 'summary':'Build a minimum-weight tree that connects every vertex. Compare the two greedy orders, Prim and Kruskal, and use union-find to make Kruskal’s cycle test cheap.',
 'objectives':['Trace Prim’s algorithm from a start vertex and Kruskal’s algorithm on a sorted edge list.','Prove the cut property and use it to justify each greedy choice.','Trace union-find with union by size and path compression and bound the cost of find.','Compare the running times of Prim and Kruskal in terms of n and m.','Explain why an MST does not in general contain shortest paths.'],
 'scope':['Spanning trees; weighted graphs','Prim’s algorithm: trace and O(n²) or O(m log n) bound','Kruskal’s algorithm: sort edges, accept if different components, O(m log m)','Cut property and the correctness of greedy MST choices','Union-find: parent array, union by size, path compression, near-constant amortised cost','Uniqueness of the MST when weights are distinct'],
 'examples':[ex('Does any tree connecting all vertices have the smallest total weight?',
 'A triangle has undirected edge weights AB=1, BC=2, AC=3. Apply Kruskal’s algorithm.',
 ['Sort the edges by weight: AB, BC, AC.','Accept AB: it joins different components.','Accept BC: all three vertices are now connected. Total weight is 3.','Reject AC because it closes a cycle. The cut property justifies choosing a lightest edge across a cut.'],
 'An MST minimises total tree weight, not every pairwise path. Here its A-to-C path weighs 3; change AC to 2.5 and the MST stays AB,BC although the direct path is shorter.',figure=10),
 ex('How does Kruskal know, quickly, that an edge would close a cycle?',
 'Elements 1–6 start as six singleton sets, with parent[i]=i and size 1. Perform union(1,2), union(3,4), union(2,4), find(4), union(5,6), union(1,3), using union by size and path compression.',
 ['union(1,2): both roots have size 1; attach 2 under 1. parent[2]=1, size[1]=2. union(3,4): likewise parent[4]=3, size[3]=2.','union(2,4): find(2)=1 and find(4)=3; the sizes are equal, so attach root 3 under root 1. parent[3]=1, size[1]=4. The set is now {1,2,3,4}.','find(4): follow 4→3→1. Path compression then sets parent[4]=1 directly, so the next find(4) takes one step. union(5,6): parent[6]=5.','union(1,3): find(1)=1 and find(3)=1 are the same root, so nothing changes. In Kruskal’s algorithm this is exactly the case where the edge is rejected because it would close a cycle.'],
 'Without union by size, unions in the order (1,2), (2,3), (3,4), … can build a chain and make one find cost Θ(n). Union by size keeps every tree of height at most lg n, so find is O(log n); with path compression the cost per operation is almost constant on average.',
 label='Core: union-find')],
 'python':'Kruskal’s cycle test is two find calls. Keep a parent list and a size list; a root is an element that is its own parent.',
 'code':'parent = list(range(7)); size = [1] * 7   # elements 1..6, index 0 unused\ndef find(x):\n    while parent[x] != x:\n        parent[x] = parent[parent[x]]   # compress the path as we go\n        x = parent[x]\n    return x\ndef union(a, b):\n    ra, rb = find(a), find(b)\n    if ra == rb:\n        return False                    # same set: this edge would close a cycle\n    if size[ra] < size[rb]:\n        ra, rb = rb, ra\n    parent[rb] = ra; size[ra] += size[rb]\n    return True\nfor a, b in [(1, 2), (3, 4), (2, 4), (5, 6), (1, 3)]:\n    print((a, b), union(a, b))\nprint(find(4), parent[1:])  # 1 [1, 1, 1, 1, 5, 5]'},
{'title':'Shortest paths: Dijkstra, Bellman–Ford, Floyd','lectures':[14],
 'summary':'Relax weighted edges and understand the condition behind Dijkstra’s algorithm. Use Bellman–Ford when weights may be negative, and Floyd for every pair at once.',
 'objectives':['Trace Dijkstra’s algorithm with distance and predecessor tables and reconstruct a path.','State the edge-weight condition Dijkstra needs and give a counterexample when it fails.','Trace one Bellman–Ford round and bound the number of rounds needed.','Derive the Floyd update rule and trace it on a three-vertex graph.','Choose among BFS, Dijkstra, Bellman–Ford and Floyd for a stated shortest-path question.'],
 'scope':['Relaxation: d(v)=min(d(v), d(u)+w(u,v)); predecessor tables','Dijkstra’s algorithm: settled-once rule, nonnegative weights, O(n²) or O(m log n)','Bellman–Ford (core): n−1 rounds of relaxing every edge, negative edges, negative-cycle detection','Floyd’s all-pairs algorithm: the k-loop update and O(n³)','Adding a constant to every edge changes the shortest path (warm-up)','Updating an MST after adding one edge (reading only)'],
 'examples':[ex('When is a tentative shortest distance safe to finalise?',
 'Directed edges A→B=2, A→C=5, B→C=1. Find distances from A.',
 ['Initial distances: A=0, B=∞, C=∞.','Settle A and relax outgoing edges: B=2, C=5.','Settle B next; the route A→B→C improves C to 2+1=3.','Settle C. Final distances are 0,2,3; predecessor links reconstruct the paths.'],
 'Dijkstra’s standard settled-once method requires nonnegative weights. With A→B=2, A→C=5, C→B=−4 it can finalise B too early, missing distance 1.',figure=11),
 ex('What does one round of Bellman–Ford guarantee?',
 'Directed edges S→A=4, S→B=2, B→A=−3, A→C=1, B→C=5. Relax every edge once, in the listed order, starting from d(S)=0 and all other distances ∞.',
 ['Relax S→A: d(A)=min(∞, 0+4)=4. Relax S→B: d(B)=min(∞, 0+2)=2.','Relax B→A: d(A)=min(4, 2−3)=−1. The negative edge improves A through B.','Relax A→C: d(C)=min(∞, −1+1)=0. Relax B→C: 2+5=7 does not improve 0. After round 1: S=0, A=−1, B=2, C=0.','Round 2 changes nothing, so the algorithm stops. In general, after round k every shortest path with at most k edges is correct, so n−1=3 rounds always suffice. If round n still changes a distance, a negative cycle is reachable.'],
 'Relax the same edges in the order A→C, B→C, B→A, S→A, S→B. Round 1 then ends with A=4, B=2, C=∞, and it takes three rounds to reach A=−1, C=0. The final answer does not depend on the order; the number of useful rounds does. Dijkstra on this graph settles B (2) before A and still finds −1 here, but with S→A=4, S→B=2, A→B=−3 it settles B at 2 and never corrects it to 1.',
 label='Core: Bellman–Ford',figure='bellman')],
 'python':'Use a distance table and predecessor table. A priority queue chooses the smallest tentative distance. Bellman–Ford needs only a loop over the edge list, repeated n−1 times.','code':11},
{'title':'Backtracking and the start of dynamic programming','lectures':[15,16],
 'summary':'Explore choices systematically, then recognise repeated subproblems. Explain what a state means before writing a recurrence.',
 'objectives':['Trace the generic backtracking routine to list all subsets or permutations of three items.','Explain pruning and estimate how much of the search tree it removes.','Compare plain recursion, memoisation and a bottom-up table for Fibonacci and bound each.','Define a dynamic-programming state and justify why equal states share an answer.'],
 'scope':['Backtracking: the generic routine (is_a_solution, construct_candidates, process_solution)','Generating all subsets and all permutations; counting the search tree','Pruning and the eight-queens idea','Recurrence relations; Fibonacci three ways: recursion, memoisation, table','The DP habit: state, transition, fill order','Binomial coefficients as a two-dimensional table','Sudoku, the backtracking contest and chessboard covering (reading only)'],
 'examples':[ex('When is remembering a smaller answer better than recomputing it?',
 'Compute Fibonacci values with F(0)=0, F(1)=1 and F(n)=F(n−1)+F(n−2).',
 ['Fill F(2)=1 and F(3)=2.','Continue F(4)=3, F(5)=5, F(6)=8.','A table computes each state once; there are n+1 states and constant work per state in the unit-cost arithmetic model.','Backtracking instead explores choices; pruning removes branches that cannot lead to a legal or useful solution.'],
 'A recurrence alone does not make an algorithm efficient. Naive Fibonacci recursion recomputes states. Large Fibonacci integers also make bit-operation cost differ from the unit-cost model.',figure=12)],
 'python':'A cache maps a state to its computed answer. Bottom-up code fills states in dependency order.'},
{'title':'Dynamic programming: edit distance, partition, TSP','lectures':[17,18],
 'summary':'Build and interpret a small edit-distance table. Extend the state–transition–order method to linear partition, and see where the principle of optimality holds but the table is too big.',
 'objectives':['Define the edit-distance state D(i,j), write its recurrence and fill a small table.','Reconstruct the edit sequence from a filled table.','Formulate linear partition as a DP: state, recurrence, fill order, cost O(kn²).','Decide whether a stated problem satisfies the principle of optimality.','Bound the number of states of a DP and recognise when it is exponential, as for TSP.'],
 'scope':['The three steps of dynamic programming','Edit distance: recurrence, table, reconstruction, O(mn)','One engine, many problems: substring matching and longest common subsequence as variants','Linear partition: recurrence and table','When can you use dynamic programming? The principle of optimality','TSP: why the principle holds but the state space is exponential','Egg dropping, two-finger dialling and bar codes (reading only)'],
 'examples':[ex('What information must a state retain for the remaining decision?',
 'Find the edit distance from cat to cut, with insertion, deletion and substitution cost 1.',
 ['Let D(i,j) be the distance between the first i source and first j target characters.','Set D(i,0)=i and D(0,j)=j.','Use the minimum of deletion D(i−1,j)+1, insertion D(i,j−1)+1 and diagonal D(i−1,j−1)+[characters differ].','Rows including the empty prefix are [0,1,2,3], [1,0,1,2], [2,1,1,2], [3,2,2,1]. The answer is 1: substitute a→u.'],
 'The final value is a cost, not the edit sequence. Retain or reconstruct predecessor choices to explain the edits. This table has O(mn) states.',figure=13)],
 'python':'Two nested loops fill rows and columns after their dependencies. Draw the table before translating it into Python.'},
{'title':'Reductions and NP-completeness','lectures':[19,20,21,22],
 'summary':'Distinguish finding from checking, explain reduction direction, and recognise what NP-completeness does and does not establish.',
 'objectives':['Explain the difference between solving a problem and checking a proposed certificate.','State the direction of a polynomial-time reduction and what it proves about each problem.','Prove that a problem is in NP by describing a certificate and a polynomial-time check.','Outline an NP-completeness proof: membership plus a reduction from a known NP-complete problem.','Distinguish what NP-completeness establishes from what P versus NP leaves open.'],
 'scope':['Reductions: direction, Bandersnatch and Bo-billy, upper and lower bounds flowing through a reduction','Problems, instances and decision problems','Satisfiability and 3-SAT as the first hard problem','Vertex cover, independent set and clique: statements and the relations between them','Subset sum (integer partition): statement and why it is hard','P, NP, NP-complete, NP-hard; what P versus NP asks','Small change, huge difference: pairs of problems in P and NP-complete','SAT gadget constructions, integer programming and the convex-hull lower bound (reading only)'],
 'examples':[ex('What can we conclude when no fast exact method is known?',
 'You want to show a decision problem X is NP-complete, using a known NP-complete problem A.',
 ['Show that proposed yes-certificates for X can be checked in polynomial time: X is in NP.','Construct a polynomial-time transformation A→X preserving yes/no answers.','A fast solver for X would then solve A quickly. This establishes NP-hardness of X.','Combine membership and hardness. This does not prove that a polynomial-time algorithm is impossible: P versus NP remains unresolved.'],
 'Reducing X to A proves that X is no harder than A; it does not establish that X is NP-hard. Detailed SAT gadget proofs are optional depth this week.',figure=14)],
 'python':'No new Python is required. Assess a method using its contract, correctness argument, cost assumptions and limitations.'},
]
assert len(WEEKS)==14

def title(n):return WEEKS[n-1]['title']
def lectures(n):return WEEKS[n-1]['lectures']
# (title, lectures) pairs for callers that only need the map.
WEEK_TUPLES=[(w['title'],w['lectures']) for w in WEEKS]
