"""Canonical 14-week topic sequence. Lecture numbers refer to the supplied bilingual notes."""
WEEKS = [
('Algorithms and correctness',[1],'Specify the answer, trace a method, and challenge a tempting rule. Robot tours and interval scheduling show why correctness needs an argument.',
 'Can a locally attractive choice give a globally bad answer?',
 'Jobs A=[0,3], B=[2,4], C=[3,5]. Choose the largest compatible set; touching endpoints are allowed.',
 ['Sort by finish time: A, B, C.','Accept A, ending at 3. Reject B because it starts at 2.','Accept C because it starts at 3. Result: two jobs.','The earliest finish leaves at least as much room as any competing first choice. Repeating this exchange establishes optimality for equal-value fixed intervals.'],
 'If jobs have different fees, maximising their count may not maximise income. We return to this distinction in dynamic programming.',
 'Variables name values; assignment stores a result. An algorithm can be explained before any Python is written.'),
('Counting work and growth',[2],'Count a chosen basic operation, distinguish input cases, and use O, Ω and Θ to describe growth. Timing is supporting evidence, not a proof.',
 'What changes when the input doubles?',
 'A procedure performs T(n)=3n²+10n basic operations. Give a tight asymptotic bound.',
 ['For n≥1, 10n≤10n², so T(n)≤13n². This proves O(n²).','Also T(n)≥3n² for n≥1, proving Ω(n²).','Together these bounds give Θ(n²). Constants do not change the growth class.','Doubling n gives a ratio approaching 4, not exactly 4 at every finite n.'],
 'An O(n³) upper bound is also true but less informative. Big-O does not itself mean worst case; first specify which cost function is being bounded.',
 'Read n*n as n². Use arithmetic to check a small case; no plotting code is required.'),
('Program analysis and logarithms',[3],'Trace simple and nested loops, derive sums, and compare selection with insertion sort. Repeated halving explains logarithmic work.',
 'When do we add counts, and when do we multiply them?',
 'An outer loop uses i=1,…,n. For each i, the inner loop performs i comparisons.',
 ['For n=4 the row counts are 1,2,3,4, totalling 10.','In general T(n)=1+2+…+n=n(n+1)/2.','The dominant term is n²/2, giving Θ(n²).','By contrast, repeatedly halving n until 1 takes about log₂n steps.'],
 'Two consecutive n-step loops give 2n, not n². Multiplication applies when one complete loop is repeated inside another.',
 'for i in range(1,n+1) visits 1 through n. Indentation shows which instructions repeat together.'),
('Arrays, linked lists, stacks and queues',[4],'Compare data structures by the operations they support. Draw storage, links, and the order in which items leave.',
 'Which operation does the problem need to be cheap?',
 'Insert 8 at the front of the packed array [2,5,7]. Then compare a singly linked list with a known head.',
 ['The array must move 7,5,2 one position right before storing 8: three moves.','For n existing items, this front insertion is Θ(n), assuming enough capacity.','For a linked list, create a node pointing to the old head, then update the head: O(1).','The tradeoff reverses for arbitrary indexed access: array O(1), linked-list traversal O(n).'],
 'Linked-list insertion is constant time only when the necessary location/link is already known. Finding it may require a full search.',
 'A Python list behaves like a dynamic array, not a linked list. A stack is last-in first-out; a queue is first-in first-out.'),
('Search trees and hashing',[5,6],'Use trees and hash tables to implement dictionaries. Relate tree height, collisions and load factor to the actual search cost.',
 'What assumptions make a lookup fast?',
 'Insert 10,15,3,20 into five hash slots using h(k)=k mod 5 and linear probing.',
 ['10 enters slot 0.','15 also hashes to 0; slot 1 is the first free slot.','3 enters slot 3.','20 probes 0,1,2 and enters slot 2. A lookup must use the same probing rule.'],
 'Deleting 10 by making slot 0 look never-used can break a later search for 20. Use a tombstone or a correct repair scheme. Expected constant lookup is conditional, not a worst-case guarantee.',
 'A dictionary stores key–value pairs. Python dict syntax is a demonstration; draw the slots before running code.'),
('Priority queues and heapsort',[7],'Maintain a partial order that makes the next minimum or maximum easy to remove. Separate one heap operation from building a whole heap.',
 'Why does a heap avoid searching every item for the next minimum?',
 'Insert 1 into the min-heap [2,4,3], using array positions starting at 1.',
 ['Append 1 at position 4: [2,4,3,1].','Compare with its parent at position 2; swap: [2,1,3,4].','Compare with the root; swap: [1,2,3,4].','There are at most O(log n) levels. Bottom-up construction of an entire heap is O(n), because most nodes have very small height.'],
 'A heap is not a fully sorted array. Its root is extreme; siblings need not be ordered. Heapsort is O(n log n) in the worst case.',
 'Parent index is i//2 with 1-based positions. Python uses 0-based lists, so keep the convention explicit.'),
('Mergesort and quicksort',[8],'Split problems into smaller parts and trace how the results combine. Compare balanced splitting with bad pivots.',
 'Where does n log n come from?',
 'Merge the sorted runs [1,4,7] and [2,3,8].',
 ['Compare the front values: choose 1, then 2, then 3.','Compare 4 with 8: choose 4. Compare 7 with 8: choose 7.','The first run is empty; append 8 without another key comparison. Five comparisons merge six items.','Mergesort handles n items per level across about log₂n levels: Θ(n log n).'],
 'Quicksort can split into sizes 0 and n−1 repeatedly, giving Θ(n²). Random pivots give an expected O(n log n) bound, not a worst-case guarantee.',
 'A recursive function calls itself on a smaller input and must have a stopping case. Trace the calls as a tree first.'),
('Sorting limits and review',[9],'Explain the comparison-sorting lower bound and how restricted integer keys permit different methods. Review correctness, counts and data structures.',
 'How can a linear-time sort coexist with an n log n lower bound?',
 'Stable radix-sort [21,13,12,23] by units, then tens.',
 ['Units pass: [21,12,13,23]. Equal units preserve input order.','Tens pass: [12,13,21,23]. Equal tens preserve the units order established earlier.','Each stable counting pass costs O(n+b) for base b. With d digits the total is O(d(n+b)).','The Ω(n log n) worst-case lower bound concerns comparison-only sorting of arbitrary distinct keys. Radix sort uses key digits.'],
 'The digit count and range matter. Calling radix sort O(n) without stating these assumptions is incomplete.',
 'Use // for integer quotient and % for remainder to isolate a digit. The main task is the paper trace.'),
('Graph representations and BFS',[10,11],'Represent networks with adjacency lists or matrices. Use a queue to discover vertices in increasing number of edges from the start.',
 'Why does BFS find the shortest unweighted path?',
 'Undirected edges: 1–2,1–3,2–4,3–4,4–5. Run BFS from 1, considering neighbours in increasing order.',
 ['Start with distance(1)=0 and queue [1].','Process 1: discover 2 and 3 at distance 1; queue [2,3].','Process 2: discover 4 at distance 2. Processing 3 does not rediscover 4.','Process 4: discover 5 at distance 3. Discovery order is 1,2,3,4,5; one shortest path is 1–2–4–5.'],
 'BFS minimises edge count; arbitrary edge weights need a different algorithm. Mark vertices when enqueued to avoid repeated insertion.',
 'A dictionary of neighbour lists represents a graph. A deque supports efficient queue removal from the front.'),
('DFS and minimum spanning trees',[12,13],'Trace depth-first exploration and distinguish a traversal tree from a minimum-weight connecting tree. Introduce topological order and greedy MST choices.',
 'Does any tree connecting all vertices have the smallest total weight?',
 'A triangle has undirected edge weights AB=1, BC=2, AC=3. Apply Kruskal’s algorithm.',
 ['Sort the edges by weight: AB, BC, AC.','Accept AB: it joins different components.','Accept BC: all three vertices are now connected. Total weight is 3.','Reject AC because it closes a cycle. The cut property justifies choosing a lightest edge across a cut.'],
 'An MST minimises total tree weight, not every pairwise path. Here its A-to-C path weighs 3; change AC to 2.5 and the MST stays AB,BC although the direct path is shorter.',
 'DFS uses recursion or an explicit stack. Track visited vertices. Union–find is a separate tool for Kruskal’s cycle checks.'),
('Shortest paths',[14],'Relax weighted edges and understand the condition behind Dijkstra’s algorithm. Contrast single-source and all-pairs questions.',
 'When is a tentative shortest distance safe to finalise?',
 'Directed edges A→B=2, A→C=5, B→C=1. Find distances from A.',
 ['Initial distances: A=0, B=∞, C=∞.','Settle A and relax outgoing edges: B=2, C=5.','Settle B next; the route A→B→C improves C to 2+1=3.','Settle C. Final distances are 0,2,3; predecessor links reconstruct the paths.'],
 'Dijkstra’s standard settled-once method requires nonnegative weights. With A→B=2, A→C=5, C→B=−4 it can finalise B too early, missing distance 1.',
 'Use a distance table and predecessor table. A priority queue chooses the smallest tentative distance.'),
('Backtracking and dynamic programming',[15,16],'Explore choices systematically, then recognise repeated subproblems. Explain what a state means before writing a recurrence.',
 'When is remembering a smaller answer better than recomputing it?',
 'Compute Fibonacci values with F(0)=0, F(1)=1 and F(n)=F(n−1)+F(n−2).',
 ['Fill F(2)=1 and F(3)=2.','Continue F(4)=3, F(5)=5, F(6)=8.','A table computes each state once; there are n+1 states and constant work per state in the unit-cost arithmetic model.','Backtracking instead explores choices; pruning removes branches that cannot lead to a legal or useful solution.'],
 'A recurrence alone does not make an algorithm efficient. Naive Fibonacci recursion recomputes states. Large Fibonacci integers also make bit-operation cost differ from the unit-cost model.',
 'A cache maps a state to its computed answer. Bottom-up code fills states in dependency order.'),
('Dynamic programming through tables',[17,18],'Build and interpret a small edit-distance table. Extend the state–transition–order method to partitioning and other selected applications.',
 'What information must a state retain for the remaining decision?',
 'Find the edit distance from cat to cut, with insertion, deletion and substitution cost 1.',
 ['Let D(i,j) be the distance between the first i source and first j target characters.','Set D(i,0)=i and D(0,j)=j.','Use the minimum of deletion D(i−1,j)+1, insertion D(i,j−1)+1 and diagonal D(i−1,j−1)+[characters differ].','Rows including the empty prefix are [0,1,2,3], [1,0,1,2], [2,1,1,2], [3,2,2,1]. The answer is 1: substitute a→u.'],
 'The final value is a cost, not the edit sequence. Retain or reconstruct predecessor choices to explain the edits. This table has O(mn) states.',
 'Two nested loops fill rows and columns after their dependencies. Draw the table before translating it into Python.'),
('Computational limits and cumulative review',[19,20,21,22],'Distinguish finding from checking, explain reduction direction, and recognise what NP-completeness does and does not establish.',
 'What can we conclude when no fast exact method is known?',
 'You want to show a decision problem X is NP-complete, using a known NP-complete problem A.',
 ['Show that proposed yes-certificates for X can be checked in polynomial time: X is in NP.','Construct a polynomial-time transformation A→X preserving yes/no answers.','A fast solver for X would then solve A quickly. This establishes NP-hardness of X.','Combine membership and hardness. This does not prove that a polynomial-time algorithm is impossible: P versus NP remains unresolved.'],
 'Reducing X to A proves that X is no harder than A; it does not establish that X is NP-hard. Detailed SAT gadget proofs are optional depth this week.',
 'No new Python is required. Assess a method using its contract, correctness argument, cost assumptions and limitations.'),
]
