"""Sample exam questions with marking notes, inserted into scope/index.html by build.py."""
MIDTERM='''<h3>Sample midterm questions</h3>
<article class="sample-question"><h3>Sample 1 · Counting and bounding (Weeks 2–3, 3 marks)</h3>
<p>A procedure runs the loop <code>for i in 1..n: for j in 1..i: step()</code> and then a second, separate loop <code>for k in 1..n: step()</code>. (a) Give the exact number of calls to <code>step()</code> as a function of n. (b) State a tight Θ bound and justify it with constants c and n<sub>0</sub> for the upper bound.</p>
<details><summary>Marking notes</summary><ul class="marking"><li>1 mark: n(n+1)/2 + n = (n² + 3n)/2 (the two loops add, they do not multiply).</li><li>1 mark: Θ(n²) stated.</li><li>1 mark: an explicit witness, e.g. (n² + 3n)/2 ≤ 2n² for all n ≥ 1, so c = 2, n<sub>0</sub> = 1; the lower bound needs only "≥ n²/2".</li><li>No mark for "it is O(n²) because of the nested loop" without the count; half a mark if the sum is written but not closed.</li></ul></details></article>
<article class="sample-question"><h3>Sample 2 · Trace and invariant (Weeks 3–5, 4 marks)</h3>
<p>(a) Insert the keys 7, 12, 2, 17, 22 into a hash table with 5 slots using h(k) = k mod 5 and linear probing. Show the table after every insertion. (b) State the loop invariant of insertion sort for the outer loop index i, and explain in two sentences why it holds after the loop finishes.</p>
<details><summary>Marking notes</summary><ul class="marking"><li>2 marks: final table [22, 7, 12, 2, 17] with 22 probing 2 → 3 → 4 → 0; one mark off for a wrong probe sequence even if the final table happens to be right.</li><li>1 mark: "before iteration i, positions 0..i−1 hold the original first i elements in sorted order."</li><li>1 mark: termination = i = n, so the invariant says the whole array is sorted; maintenance is why it stays true, testing on examples is not a proof.</li></ul></details></article>'''
FINAL='''<h3>Sample final questions</h3>
<article class="sample-question"><h3>Sample 3 · Shortest paths (Week 11, 4 marks)</h3>
<p>Run Dijkstra from S on the directed graph S→A (2), S→B (5), A→B (1), A→C (6), B→C (2). Show the tentative distances after each vertex is settled, and give the final distances and predecessors. Then change the weight of A→B to −4 and explain, with the first wrong step, why Dijkstra can fail and which algorithm you would use instead.</p>
<details><summary>Marking notes</summary><ul class="marking"><li>2 marks: settle order S, A, B, C; distances S 0, A 2, B 3, C 5; predecessors A←S, B←A, C←B.</li><li>1 mark: with A→B = −4 the true d(B) = −2, and B may be settled at 5 or C at 5 before the negative edge is relaxed — the "settled is final" argument needs non-negative weights.</li><li>1 mark: Bellman–Ford (|V|−1 rounds of relaxing all edges, O(VE)), or a sentence that Floyd handles negative edges without negative cycles.</li></ul></details></article>
<article class="sample-question"><h3>Sample 4 · Recurrence and dynamic programming (Weeks 7, 12–13, 4 marks)</h3>
<p>(a) Solve T(n) = 2T(n/2) + n with T(1) = 1 using the recursion tree, and check the result with the master theorem. (b) Write the recurrence for the edit distance D[i, j] between the first i letters of one word and the first j letters of another, state the base cases, and fill the table for "cat" and "cut".</p>
<details><summary>Marking notes</summary><ul class="marking"><li>1 mark: lg n + 1 levels, each of cost n, total Θ(n log n); 1 mark: a = 2, b = 2, d = 1, log<sub>b</sub> a = d ⇒ case 2.</li><li>1 mark: D[i, j] = min(D[i−1, j] + 1, D[i, j−1] + 1, D[i−1, j−1] + [letters differ]); D[i, 0] = i, D[0, j] = j.</li><li>1 mark: correct 4×4 table with D[3, 3] = 1; a table with the right corner but wrong interior earns half.</li></ul></details></article>'''
