/* Small, deterministic teaching models. No Python execution, network or grading. */
(() => {
  'use strict';
  const host = document.querySelector('[data-cp1-lab]');
  if (!host) return;
  const week = Number(host.dataset.cp1Lab);
  const el = (tag, cls, text) => { const node = document.createElement(tag); node.className = cls || ''; if (text !== undefined) node.textContent = text; return node; };
  const frame = (text, values, active = -1, result = '') => ({text, values: values.map(String), active, result});
  const models = {
    1: {title:'Watch a wheel accumulate distance', prompt:'Compare a 60 mm and a 70 mm wheel after the same ten turns.', limit:'Ideal rolling without slip. Playback is slowed teaching time, not motor speed.', controls:[['Diameter (mm)',60,70,.5,65]], build:([d]) => Array.from({length:11},(_,i)=>frame(`${i} turns × π × ${d} mm ÷ 1000`,[`${i} turns`,`${d} mm`,`${(i*Math.PI*d/1000).toFixed(3)} m`],i,`Ideal travel: ${(i*Math.PI*d/1000).toFixed(3)} m`))},
    2: {title:'Same display, different inspection result', prompt:'Try 10.049 and 10.051 mm. Change display precision without changing the measurement.', limit:'Exact input values in this model; measurement uncertainty is not included. Acceptance limits are inclusive.', controls:[['Measured diameter (mm)',9.94,10.06,.001,10.049],['Display decimals',0,3,1,0]], build:([x,p])=>[
      frame('Keep the original measurement.',[`${x.toFixed(3)} mm`],0),
      frame('Format a separate value for the operator display.',[`${x.toFixed(3)} mm`,`${x.toFixed(p)} mm`],1),
      frame('Compare the original measurement with 9.950–10.050 mm.',[`${x.toFixed(3)} mm`,`${x.toFixed(p)} mm`,x>=9.95&&x<=10.05?'ACCEPT':'REJECT'],2,`Display precision changes the message, not the decision: ${x>=9.95&&x<=10.05?'ACCEPT':'REJECT'}.`)]},
    3: {title:'Follow the enable decision', prompt:'Open the guard at 25 °C, then compare AND with the faulty OR rule. Also test exactly 60 °C.', limit:'A logic teaching model, not a hardware safety interlock. The run request is present.', controls:[['Temperature (°C)',20,80,1,60],['Guard',['Closed','Open']],['Operator',['AND','OR (fault)']]], build:([t,g,op])=>{const closed=g===0,cool=t<60,ok=op===0?closed&&cool:closed||cool;return [frame(`Guard closed → ${closed}`,[closed?'Closed':'Open','Temperature','Decision'],0),frame(`${t} < 60 → ${cool}`,[closed?'Closed':'Open',`${t} °C: ${cool}`,'Decision'],1),frame(`${closed} ${op===0?'AND':'OR'} ${cool} → ${ok}`,[closed?'Closed':'Open',`${t} °C`,ok?'ENABLE':'DENY'],2,`${ok?'ENABLE':'DENY'}${op===1?' — compare this faulty rule with the requirement.':''}`)];}},
    4: {title:'Watch the samples meet—or miss—the pulse', prompt:'Try a 300 ms interval, then 100 ms. Move the offset to change where the first sample falls.', limit:'The signal is high at 200 ≤ t < 300 ms. Only sample instants are observed; playback is not real-time acquisition.', controls:[['Sample interval (ms)',50,350,50,100],['First sample (ms)',0,100,25,0]], build:([dt,offset])=>{const ts=[];for(let t=offset;t<=500;t+=dt)ts.push(t);let hits=0;return [frame('The pulse exists before we observe it.',ts.map(t=>`${t} ms`))].concat(ts.map((t,i)=>{if(t>=200&&t<300)hits++;return frame(`Read at ${t} ms: ${t>=200&&t<300?'HIGH':'low'}.`,ts.map((v,j)=>`${v} ms: ${j<=i?(v>=200&&v<300?'HIGH':'low'):'?'}`),i,`${hits} HIGH / ${i+1} samples observed`);}));}},
    5: {title:'A search that always stops', prompt:'Put the reference beyond the move limit. Then bring it exactly onto the limit.', limit:'One move advances one ideal position. Switch noise and physical motion are not simulated.', controls:[['Reference position',1,9,1,5],['Maximum moves',1,8,1,5]], build:([target,max])=>{const frames=[];for(let p=0;p<=Math.min(target,max);p++)frames.push(frame(`position = ${p}; continue only if position < ${target} AND position < ${max}.`,Array.from({length:10},(_,i)=>i===target?`${i} · REF`:i),p,p===Math.min(target,max)?(p>=target?'REFERENCE FOUND':'SEARCH LIMIT REACHED'):`Moves used: ${p}/${max}`));return frames;}},
    6: {title:'Watch the mean hide a peak', prompt:'Compare steady readings with a sequence that has the same mean and a short peak.', limit:'Five equally weighted samples. A mean alone cannot establish whether a limit was exceeded.', controls:[['Readings',['4, 4, 4, 8, 0','4, 4, 4, 4, 4']]], build:([mode])=>{const a=mode===0?[4,4,4,8,0]:[4,4,4,4,4];let sum=0,peak=-Infinity,high=0;return [frame('Start with no observations accumulated.',a)].concat(a.map((v,i)=>{sum+=v;peak=Math.max(peak,v);high+=v>6?1:0;return frame(`Add ${v}; keep the count, peak and number above 6.`,a,i,`Mean ${(sum/(i+1)).toFixed(2)} · peak ${peak} · above 6: ${high}`);}));}},
    7: {title:'Keep time order when sorting', prompt:'Compare sorting a copy with sorting the original. Where was the peak acquired?', limit:'Index means acquisition position, starting at zero. Sorting changes positions, not the recorded values.', controls:[['Sort target',['Copy','Original (loses order)']]], build:([mode])=>{const raw=[0,2,2,9,3],sorted=[0,2,2,3,9];return [frame('Raw acquisition order: the peak arrived at index 3.',raw,3,'Raw peak index: 3'),frame(mode===0?'Copy before changing the order.':'The analysis name refers to the original list.',raw,-1,mode===0?'raw and analysis are separate lists':'raw and analysis refer to the same list'),frame('The sorted view puts 9 at index 4.',sorted,4,'Sorted peak index: 4'),frame(mode===0?'Return to the preserved raw observations.':'The original order has been overwritten.',mode===0?raw:sorted,mode===0?3:4,mode===0?'Acquisition peak index is still 3.':'Index 4 now means sorted position; acquisition position was lost.')];}},
    8: {title:'Scan a temperature grid', prompt:'Move the hot spot. Follow row and column together, rather than keeping only the peak value.', limit:'Two rows and three columns; all positions use zero-based indexing.', controls:[['Hot spot row',0,1,1,1],['Hot spot column',0,2,1,1]], build:([row,col])=>{const a=[22,23,24,25,26,27];a[row*3+col]=80;let best=a[0],loc=0;return [frame('Initial peak comes from grid[0][0].',a,0,'Peak '+best+' °C at (0, 0)')].concat(a.map((v,i)=>{if(v>best){best=v;loc=i;}return frame(`Inspect grid[${Math.floor(i/3)}][${i%3}] = ${v} °C.`,a,i,`Peak ${best} °C at (${Math.floor(loc/3)}, ${loc%3})`);}));}},
    9: {title:'Unpack a device message', prompt:'Compare a valid record, a wrong unit and a value that only looks structurally valid.', limit:'This stage checks fields and identifiers. Numeric validation is a separate step.', controls:[['Message',[' T1,23.5,C ','T1,23.5,F','T1,bad,C','T1,23.5']]], build:([mode])=>{const raw=[' T1,23.5,C ','T1,23.5,F','T1,bad,C','T1,23.5'][mode],fields=raw.trim().split(',');const ok=fields.length===3&&fields[0]==='T1'&&fields[2]==='C';return [frame('Receive the raw text.',[JSON.stringify(raw)],0),frame('strip() removes outside whitespace; split(",") separates fields.',fields,-1,`${fields.length} fields`),frame('Require three fields, sensor T1 and unit C.',fields,-1,ok?'STRUCTURE OK — numeric validation still required':'REJECT: unexpected structure or unit')];}},
    10: {title:'Move along the calibration line', prompt:'Follow the conversion, then try 0.5 V, 4.5 V and a voltage outside that interval.', limit:'Teaching calibration: 0.5–4.5 V maps linearly to 0–100 N. Outside this range the calculated value is unvalidated extrapolation.', controls:[['Voltage (V)',0,5,.1,2.5]], build:([v])=>[frame('Receive voltage in volts.',[`${v.toFixed(1)} V`],0),frame('Subtract the 0.5 V zero offset.',[`${v.toFixed(1)} V`,`${(v-.5).toFixed(1)} V`],1),frame('Multiply by 25 N/V.',[`${v.toFixed(1)} V`,`${(v-.5).toFixed(1)} V`,`${((v-.5)*25).toFixed(1)} N`],2,v>=.5&&v<=4.5?'Within the calibration interval':'OUTSIDE calibration interval — unvalidated extrapolation')]},
    11: {title:'One function, two calibrations', prompt:'Run A, then B, then A again. A must give the same result on both calls.', limit:'The input and calibration are explicit arguments. No hidden shared calibration is changed.', controls:[['Voltage (V)',1,4,.1,2.5]], build:([v])=>[frame('Prepare two independent calibration records.',['A: offset 0.5 V','B: offset 1.0 V','Gain: 25 N/V']),...['A','B','A'].map((name,i)=>{const off=name==='A'?.5:1;return frame(`convert(${v.toFixed(1)}, sensor_${name.toLowerCase()})`,[name,`${v.toFixed(1)} − ${off}`,`${((v-off)*25).toFixed(1)} N`],2,`Call ${i+1}: ${name} returns ${((v-off)*25).toFixed(1)} N`);})]},
    12: {title:'Missing is not zero', prompt:'Compare 0 with an empty field and nan. Follow the first rule that rejects each value.', limit:'Accepted temperatures are finite numbers from −50 to 60 °C inclusive.', controls:[['Raw field',['0','-10','(empty)','bad','nan','61']]], build:([mode])=>{const raw=['0','-10','','bad','nan','61'][mode];const frames=[frame('Receive raw text.',[raw===''?'empty':raw],0)];if(!raw)return frames.concat(frame('Stop: no measurement was supplied.',['empty','REJECT'],1,'REJECT: empty value'));frames.push(frame('Non-empty text proceeds to numeric conversion.',[raw,'parse'],1));if(raw==='bad')return frames.concat(frame('The text is not a number.',[raw,'REJECT'],1,'REJECT: non-numeric value'));if(raw==='nan')return frames.concat(frame('nan is not a finite measurement.',[raw,'REJECT'],1,'REJECT: nonfinite value'));const x=Number(raw);return frames.concat(frame('Check the inclusive physical range.',[raw,Number.isFinite(x)&&x>=-50&&x<=60?'ACCEPT':'REJECT'],1,x>=-50&&x<=60?`ACCEPT: ${x} °C`:'REJECT: out of range'));}},
    13: {title:'Follow rows into an auditable report', prompt:'Switch the middle row between bad and 0. A valid zero should be retained.', limit:'A three-row, fixed-schema example. The file preview is in memory; this demo does not write to your disk.', controls:[['Middle value',['bad','0']]], build:([mode])=>{const a=['20',mode===0?'bad':'0','22'],clean=[],reject=[],frames=[frame('Preserve the three raw rows before processing.',a)];a.forEach((v,i)=>{if(v==='bad')reject.push(i+2);else clean.push(Number(v));frames.push(frame(`Read file line ${i+2}: T1,${v}`,a,i,`Retained ${clean.length} · rejected ${reject.length} · accounted for ${i+1}`));});frames.push(frame('Preview the saved clean CSV; keep rejection line numbers.', ['sensor,temperature_c',...clean.map(v=>`T1,${v}`)],-1,`Reopen check: ${clean.length} data rows. Rejected source lines: ${reject.join(', ')||'none'}.`));return frames;}},
    14: {title:'Keep data quality beside the result', prompt:'Add rejected rows while keeping the six valid temperatures fixed. Which result changes?', limit:'A small synthetic pipeline: six valid T1,C records plus malformed records. Retained-row rate describes this input file, not sensor accuracy.', controls:[['Malformed rows',0,6,1,2]], build:([bad])=>{const temps=[22.5,23.1,22.8,23.5,24,22.2],mean=temps.reduce((a,b)=>a+b,0)/temps.length,total=temps.length+bad;return [frame('Read the synthetic input file.',[`${total} raw rows`],0),frame('Check record structure, unit and numeric values.',[`${total} raw`,`${temps.length} retained`,`${bad} rejected`],1,`${temps.length} + ${bad} = ${total}: every row accounted for`),frame('Summarise only the six valid temperatures.',temps,-1,`Mean temperature: ${mean.toFixed(2)} °C`),frame('Report the result and the retained-row rate together.',[`${mean.toFixed(2)} °C`,`${(100*temps.length/total).toFixed(1)}% retained`],1,`Same valid mean; ${bad} rejected rows remain visible in the quality report.`)];}}
  };
  const model = models[week];
  host.append(el('p','eyebrow','Interactive bench · ungraded practice'),el('h3','',model.title),el('p','',model.prompt));
  const settings=el('div','lab-settings');host.append(settings);
  const inputs=model.controls.map((c,i)=>{const wrap=el('div'),label=el('label','',c[0]);label.htmlFor=`lab-input-${i}`;wrap.append(label);let input;
    if(Array.isArray(c[1])){input=el('select');c[1].forEach((name,j)=>{const option=el('option','',name);option.value=j;input.append(option);});}
    else {input=el('input');input.type='range';[input.min,input.max,input.step,input.value]=c.slice(1).map(String);}
    input.id=label.htmlFor;wrap.append(input);const value=el('output','lab-value');wrap.append(value);settings.append(wrap);return {input,value};});
  const controls=el('div','lab-controls'),back=el('button','','Back'),play=el('button','','Play'),next=el('button','','Step'),reset=el('button','','Reset'),count=el('span','lab-count');
  [back,play,next,reset].forEach(b=>b.type='button');controls.append(back,play,next,reset,count);host.append(controls);
  const scene=el('div','lab-scene');scene.setAttribute('role','img');host.append(scene);
  const board=el('div',`lab-board${week===8?' lab-grid':''}`);host.append(board);
  const caption=el('p','lab-caption'),result=el('output','lab-result');result.setAttribute('aria-live','polite');host.append(caption,result,el('p','lab-limit',model.limit));
  let frames=[],index=0,timer=null;
  const stop=()=>{clearInterval(timer);timer=null;play.textContent='Play';};
  function draw(){const f=frames[index];board.replaceChildren(...f.values.map((v,i)=>el('div',`lab-tile${i===f.active?' active':''}`,v)));caption.textContent=f.text;result.textContent=f.result||'Follow one step at a time.';count.textContent=`${index+1} / ${frames.length}`;back.disabled=index===0;next.disabled=index===frames.length-1;
    // A physical scene for travel and sampling; the other benches show the data being processed.
    scene.hidden=![1,4,5].includes(week);scene.replaceChildren();
    if(week===1){const wheel=el('div','lab-wheel','↑');wheel.style.transform=`rotate(${index*360}deg)`;const track=el('div','lab-track');const dot=el('div','lab-dot');dot.style.left=`${index*Number(inputs[0].input.value)/70*9}%`;dot.append(wheel);track.append(dot);scene.append(track);scene.setAttribute('aria-label',`${index} turns, ${f.values[2]} ideal travel. Diagram position is schematic.`);}
    if(week===5){const track=el('div','lab-track');const marker=el('div','lab-marker','REF');marker.style.left=`${Number(inputs[0].input.value)*10}%`;const dot=el('div','lab-dot','●');dot.style.left=`${index*10}%`;track.append(marker,dot);scene.append(track);scene.setAttribute('aria-label',`Position ${index}, reference ${inputs[0].input.value}.`);}
    if(week===4){const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 520 110');const path=document.createElementNS(ns,'path');path.setAttribute('d','M10 85H210V20H310V85H510');svg.append(path);for(let j=0;j<index;j++){const t=Number(inputs[1].input.value)+j*Number(inputs[0].input.value),circle=document.createElementNS(ns,'circle');circle.setAttribute('cx',t+10);circle.setAttribute('cy',t>=200&&t<300?20:85);circle.setAttribute('r',6);svg.append(circle);}scene.append(svg);scene.setAttribute('aria-label','High pulse from 200 to 300 ms; observed samples shown as dots. '+f.result);}
  }
  function rebuild(){stop();inputs.forEach(({input,value})=>{value.textContent=input.tagName==='SELECT'?input.selectedOptions[0].textContent:input.value;});frames=model.build(inputs.map(({input})=>Number(input.value)));index=0;draw();}
  inputs.forEach(({input})=>input.addEventListener('input',rebuild));back.addEventListener('click',()=>{stop();index=Math.max(0,index-1);draw();});next.addEventListener('click',()=>{stop();index=Math.min(frames.length-1,index+1);draw();});reset.addEventListener('click',()=>{stop();index=0;draw();});play.addEventListener('click',()=>{if(timer){stop();return;}if(index===frames.length-1)index=0;play.textContent='Pause';draw();timer=setInterval(()=>{index++;draw();if(index===frames.length-1)stop();},1000);});document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});
  rebuild();host.dataset.ready='true';
})();
